namespace YashAksh
{
	// Token: 0x02000041 RID: 65
	[global::Microsoft.VisualBasic.CompilerServices.DesignerGenerated]
	public partial class Find_Sauda_Entry : global::System.Windows.Forms.Form
	{
		// Token: 0x06000CE0 RID: 3296 RVA: 0x0030AA44 File Offset: 0x00308E44
		[global::System.Diagnostics.DebuggerNonUserCode]
		protected override void Dispose(bool disposing)
		{
			try
			{
				if (disposing && this.components != null)
				{
					this.components.Dispose();
				}
			}
			finally
			{
				base.Dispose(disposing);
			}
		}

		// Token: 0x06000CE1 RID: 3297 RVA: 0x0030AA84 File Offset: 0x00308E84
		[global::System.Diagnostics.DebuggerStepThrough]
		private void InitializeComponent()
		{
			global::System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle = new global::System.Windows.Forms.DataGridViewCellStyle();
			global::System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle2 = new global::System.Windows.Forms.DataGridViewCellStyle();
			global::System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle3 = new global::System.Windows.Forms.DataGridViewCellStyle();
			global::System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle4 = new global::System.Windows.Forms.DataGridViewCellStyle();
			global::System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle5 = new global::System.Windows.Forms.DataGridViewCellStyle();
			global::System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle6 = new global::System.Windows.Forms.DataGridViewCellStyle();
			global::System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle7 = new global::System.Windows.Forms.DataGridViewCellStyle();
			this.DataGridView1 = new global::System.Windows.Forms.DataGridView();
			this.Column1 = new global::System.Windows.Forms.DataGridViewTextBoxColumn();
			this.Column2 = new global::System.Windows.Forms.DataGridViewTextBoxColumn();
			this.Column3 = new global::System.Windows.Forms.DataGridViewTextBoxColumn();
			this.Column4 = new global::System.Windows.Forms.DataGridViewTextBoxColumn();
			this.Column5 = new global::System.Windows.Forms.DataGridViewTextBoxColumn();
			this.Column6 = new global::System.Windows.Forms.DataGridViewTextBoxColumn();
			this.GroupBox2 = new global::System.Windows.Forms.GroupBox();
			this.txtteam = new global::System.Windows.Forms.TextBox();
			this.txtrate = new global::System.Windows.Forms.TextBox();
			this.txtamount = new global::System.Windows.Forms.TextBox();
			this.txtname = new global::System.Windows.Forms.ComboBox();
			this.Rteam = new global::System.Windows.Forms.RadioButton();
			this.Rrate = new global::System.Windows.Forms.RadioButton();
			this.Ramunt = new global::System.Windows.Forms.RadioButton();
			this.RA = new global::System.Windows.Forms.RadioButton();
			this.Button1 = new global::System.Windows.Forms.Button();
			this.GroupBox3 = new global::System.Windows.Forms.GroupBox();
			this.txtsname = new global::System.Windows.Forms.ComboBox();
			this.txtsrun = new global::System.Windows.Forms.TextBox();
			this.txtsrate = new global::System.Windows.Forms.TextBox();
			this.txtsamount = new global::System.Windows.Forms.TextBox();
			this.sessionall = new global::System.Windows.Forms.ComboBox();
			this.Label1 = new global::System.Windows.Forms.Label();
			this.SRUN = new global::System.Windows.Forms.RadioButton();
			this.SR = new global::System.Windows.Forms.RadioButton();
			this.SA = new global::System.Windows.Forms.RadioButton();
			this.SN = new global::System.Windows.Forms.RadioButton();
			this.Button2 = new global::System.Windows.Forms.Button();
			this.Label2 = new global::System.Windows.Forms.Label();
			this.Panel1 = new global::System.Windows.Forms.Panel();
			this.Panel2 = new global::System.Windows.Forms.Panel();
			this.DataGridView3 = new global::System.Windows.Forms.DataGridView();
			this.DataGridViewTextBoxColumn1 = new global::System.Windows.Forms.DataGridViewTextBoxColumn();
			this.DataGridViewTextBoxColumn2 = new global::System.Windows.Forms.DataGridViewTextBoxColumn();
			this.DataGridViewTextBoxColumn3 = new global::System.Windows.Forms.DataGridViewTextBoxColumn();
			this.DataGridViewTextBoxColumn4 = new global::System.Windows.Forms.DataGridViewTextBoxColumn();
			this.DataGridViewTextBoxColumn5 = new global::System.Windows.Forms.DataGridViewTextBoxColumn();
			this.DataGridViewTextBoxColumn6 = new global::System.Windows.Forms.DataGridViewTextBoxColumn();
			this.DataGridViewTextBoxColumn7 = new global::System.Windows.Forms.DataGridViewTextBoxColumn();
			this.DataGridViewTextBoxColumn8 = new global::System.Windows.Forms.DataGridViewTextBoxColumn();
			this.DataGridViewTextBoxColumn9 = new global::System.Windows.Forms.DataGridViewTextBoxColumn();
			this.DataGridViewTextBoxColumn10 = new global::System.Windows.Forms.DataGridViewTextBoxColumn();
			this.DataGridViewTextBoxColumn11 = new global::System.Windows.Forms.DataGridViewTextBoxColumn();
			this.DataGridView2 = new global::System.Windows.Forms.DataGridView();
			this.Column7 = new global::System.Windows.Forms.DataGridViewTextBoxColumn();
			this.Column8 = new global::System.Windows.Forms.DataGridViewTextBoxColumn();
			this.Column9 = new global::System.Windows.Forms.DataGridViewTextBoxColumn();
			this.Column10 = new global::System.Windows.Forms.DataGridViewTextBoxColumn();
			this.Column11 = new global::System.Windows.Forms.DataGridViewTextBoxColumn();
			this.Column12 = new global::System.Windows.Forms.DataGridViewTextBoxColumn();
			this.Column13 = new global::System.Windows.Forms.DataGridViewTextBoxColumn();
			this.Column14 = new global::System.Windows.Forms.DataGridViewTextBoxColumn();
			this.Column15 = new global::System.Windows.Forms.DataGridViewTextBoxColumn();
			this.Column16 = new global::System.Windows.Forms.DataGridViewTextBoxColumn();
			this.Column17 = new global::System.Windows.Forms.DataGridViewTextBoxColumn();
			this.Column18 = new global::System.Windows.Forms.DataGridViewTextBoxColumn();
			this.Column19 = new global::System.Windows.Forms.DataGridViewTextBoxColumn();
			this.testnu = new global::System.Windows.Forms.TextBox();
			this.Button3 = new global::System.Windows.Forms.Button();
			this.txtnu = new global::System.Windows.Forms.TextBox();
			this.txtsid = new global::System.Windows.Forms.ComboBox();
			this.Panel3 = new global::System.Windows.Forms.Panel();
			((global::System.ComponentModel.ISupportInitialize)this.DataGridView1).BeginInit();
			this.GroupBox2.SuspendLayout();
			this.GroupBox3.SuspendLayout();
			this.Panel1.SuspendLayout();
			this.Panel2.SuspendLayout();
			((global::System.ComponentModel.ISupportInitialize)this.DataGridView3).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.DataGridView2).BeginInit();
			this.SuspendLayout();
			this.DataGridView1.AllowUserToDeleteRows = false;
			this.DataGridView1.AllowUserToOrderColumns = true;
			this.DataGridView1.AllowUserToResizeColumns = false;
			this.DataGridView1.AllowUserToResizeRows = false;
			this.DataGridView1.BackgroundColor = global::System.Drawing.Color.White;
			this.DataGridView1.BorderStyle = global::System.Windows.Forms.BorderStyle.None;
			dataGridViewCellStyle.Alignment = global::System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
			dataGridViewCellStyle.BackColor = global::System.Drawing.Color.LightSteelBlue;
			dataGridViewCellStyle.Font = new global::System.Drawing.Font("Arial", 9.75f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			dataGridViewCellStyle.ForeColor = global::System.Drawing.Color.White;
			dataGridViewCellStyle.SelectionBackColor = global::System.Drawing.Color.LightSteelBlue;
			dataGridViewCellStyle.SelectionForeColor = global::System.Drawing.Color.White;
			dataGridViewCellStyle.WrapMode = global::System.Windows.Forms.DataGridViewTriState.True;
			this.DataGridView1.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle;
			this.DataGridView1.ColumnHeadersHeightSizeMode = global::System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.AutoSize;
			this.DataGridView1.Columns.AddRange(new global::System.Windows.Forms.DataGridViewColumn[]
			{
				this.Column1,
				this.Column2,
				this.Column3,
				this.Column4,
				this.Column5,
				this.Column6
			});
			this.DataGridView1.Dock = global::System.Windows.Forms.DockStyle.Fill;
			this.DataGridView1.EnableHeadersVisualStyles = false;
			this.DataGridView1.GridColor = global::System.Drawing.SystemColors.Control;
			global::System.Windows.Forms.Control dataGridView = this.DataGridView1;
			global::System.Drawing.Point location = new global::System.Drawing.Point(0, 0);
			dataGridView.Location = location;
			this.DataGridView1.Name = "DataGridView1";
			this.DataGridView1.ReadOnly = true;
			this.DataGridView1.RowHeadersVisible = false;
			this.DataGridView1.SelectionMode = global::System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
			global::System.Windows.Forms.Control dataGridView2 = this.DataGridView1;
			global::System.Drawing.Size size = new global::System.Drawing.Size(889, 155);
			dataGridView2.Size = size;
			this.DataGridView1.TabIndex = 0;
			this.Column1.HeaderText = "Date";
			this.Column1.Name = "Column1";
			this.Column1.ReadOnly = true;
			this.Column2.HeaderText = "Venue";
			this.Column2.Name = "Column2";
			this.Column2.ReadOnly = true;
			this.Column3.HeaderText = "Type";
			this.Column3.Name = "Column3";
			this.Column3.ReadOnly = true;
			this.Column3.Width = 120;
			this.Column4.HeaderText = "Team1";
			this.Column4.Name = "Column4";
			this.Column4.ReadOnly = true;
			this.Column4.Width = 150;
			this.Column5.HeaderText = "Team2";
			this.Column5.Name = "Column5";
			this.Column5.ReadOnly = true;
			this.Column5.Width = 150;
			this.Column6.HeaderText = "Result";
			this.Column6.Name = "Column6";
			this.Column6.ReadOnly = true;
			this.Column6.Width = 150;
			this.GroupBox2.Controls.Add(this.txtteam);
			this.GroupBox2.Controls.Add(this.txtrate);
			this.GroupBox2.Controls.Add(this.txtamount);
			this.GroupBox2.Controls.Add(this.txtname);
			this.GroupBox2.Controls.Add(this.Rteam);
			this.GroupBox2.Controls.Add(this.Rrate);
			this.GroupBox2.Controls.Add(this.Ramunt);
			this.GroupBox2.Controls.Add(this.RA);
			this.GroupBox2.Font = new global::System.Drawing.Font("Arial", 9.75f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.GroupBox2.ForeColor = global::System.Drawing.Color.FromArgb(64, 64, 64);
			global::System.Windows.Forms.Control groupBox = this.GroupBox2;
			location = new global::System.Drawing.Point(2, 184);
			groupBox.Location = location;
			this.GroupBox2.Name = "GroupBox2";
			global::System.Windows.Forms.Control groupBox2 = this.GroupBox2;
			size = new global::System.Drawing.Size(390, 181);
			groupBox2.Size = size;
			this.GroupBox2.TabIndex = 2;
			this.GroupBox2.TabStop = false;
			this.GroupBox2.Text = "Fo Match";
			this.txtteam.CharacterCasing = global::System.Windows.Forms.CharacterCasing.Upper;
			this.txtteam.Font = new global::System.Drawing.Font("Arial", 9.75f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			global::System.Windows.Forms.Control txtteam = this.txtteam;
			location = new global::System.Drawing.Point(146, 149);
			txtteam.Location = location;
			this.txtteam.Name = "txtteam";
			global::System.Windows.Forms.Control txtteam2 = this.txtteam;
			size = new global::System.Drawing.Size(207, 22);
			txtteam2.Size = size;
			this.txtteam.TabIndex = 14;
			this.txtrate.CharacterCasing = global::System.Windows.Forms.CharacterCasing.Upper;
			this.txtrate.Font = new global::System.Drawing.Font("Arial", 9.75f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			global::System.Windows.Forms.Control txtrate = this.txtrate;
			location = new global::System.Drawing.Point(146, 108);
			txtrate.Location = location;
			this.txtrate.Name = "txtrate";
			global::System.Windows.Forms.Control txtrate2 = this.txtrate;
			size = new global::System.Drawing.Size(209, 22);
			txtrate2.Size = size;
			this.txtrate.TabIndex = 13;
			this.txtamount.CharacterCasing = global::System.Windows.Forms.CharacterCasing.Upper;
			this.txtamount.Font = new global::System.Drawing.Font("Arial", 9.75f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			global::System.Windows.Forms.Control txtamount = this.txtamount;
			location = new global::System.Drawing.Point(146, 68);
			txtamount.Location = location;
			this.txtamount.Name = "txtamount";
			global::System.Windows.Forms.Control txtamount2 = this.txtamount;
			size = new global::System.Drawing.Size(207, 22);
			txtamount2.Size = size;
			this.txtamount.TabIndex = 12;
			this.txtname.DropDownStyle = global::System.Windows.Forms.ComboBoxStyle.Simple;
			this.txtname.Font = new global::System.Drawing.Font("Arial", 9.75f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.txtname.FormattingEnabled = true;
			global::System.Windows.Forms.Control txtname = this.txtname;
			location = new global::System.Drawing.Point(146, 24);
			txtname.Location = location;
			this.txtname.Name = "txtname";
			global::System.Windows.Forms.Control txtname2 = this.txtname;
			size = new global::System.Drawing.Size(207, 24);
			txtname2.Size = size;
			this.txtname.TabIndex = 11;
			this.Rteam.BackColor = global::System.Drawing.Color.LightSteelBlue;
			this.Rteam.FlatAppearance.BorderSize = 2;
			this.Rteam.FlatAppearance.CheckedBackColor = global::System.Drawing.Color.Red;
			this.Rteam.FlatAppearance.MouseDownBackColor = global::System.Drawing.Color.FromArgb(192, 192, 0);
			this.Rteam.FlatAppearance.MouseOverBackColor = global::System.Drawing.Color.FromArgb(192, 0, 192);
			this.Rteam.Font = new global::System.Drawing.Font("Arial", 9.75f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Rteam.ForeColor = global::System.Drawing.Color.White;
			global::System.Windows.Forms.Control rteam = this.Rteam;
			location = new global::System.Drawing.Point(9, 149);
			rteam.Location = location;
			this.Rteam.Name = "Rteam";
			global::System.Windows.Forms.Control rteam2 = this.Rteam;
			size = new global::System.Drawing.Size(129, 23);
			rteam2.Size = size;
			this.Rteam.TabIndex = 3;
			this.Rteam.TabStop = true;
			this.Rteam.Text = "Team";
			this.Rteam.UseVisualStyleBackColor = false;
			this.Rrate.BackColor = global::System.Drawing.Color.LightSteelBlue;
			this.Rrate.FlatAppearance.BorderSize = 2;
			this.Rrate.FlatAppearance.CheckedBackColor = global::System.Drawing.Color.Red;
			this.Rrate.FlatAppearance.MouseDownBackColor = global::System.Drawing.Color.FromArgb(192, 192, 0);
			this.Rrate.FlatAppearance.MouseOverBackColor = global::System.Drawing.Color.FromArgb(192, 0, 192);
			this.Rrate.Font = new global::System.Drawing.Font("Arial", 9.75f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Rrate.ForeColor = global::System.Drawing.Color.White;
			global::System.Windows.Forms.Control rrate = this.Rrate;
			location = new global::System.Drawing.Point(7, 108);
			rrate.Location = location;
			this.Rrate.Name = "Rrate";
			global::System.Windows.Forms.Control rrate2 = this.Rrate;
			size = new global::System.Drawing.Size(129, 23);
			rrate2.Size = size;
			this.Rrate.TabIndex = 2;
			this.Rrate.TabStop = true;
			this.Rrate.Text = "Bhav (Rate)";
			this.Rrate.UseVisualStyleBackColor = false;
			this.Ramunt.BackColor = global::System.Drawing.Color.LightSteelBlue;
			this.Ramunt.FlatAppearance.BorderSize = 2;
			this.Ramunt.FlatAppearance.CheckedBackColor = global::System.Drawing.Color.Red;
			this.Ramunt.FlatAppearance.MouseDownBackColor = global::System.Drawing.Color.FromArgb(192, 192, 0);
			this.Ramunt.FlatAppearance.MouseOverBackColor = global::System.Drawing.Color.FromArgb(192, 0, 192);
			this.Ramunt.Font = new global::System.Drawing.Font("Arial", 9.75f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Ramunt.ForeColor = global::System.Drawing.Color.White;
			global::System.Windows.Forms.Control ramunt = this.Ramunt;
			location = new global::System.Drawing.Point(9, 67);
			ramunt.Location = location;
			this.Ramunt.Name = "Ramunt";
			global::System.Windows.Forms.Control ramunt2 = this.Ramunt;
			size = new global::System.Drawing.Size(129, 23);
			ramunt2.Size = size;
			this.Ramunt.TabIndex = 1;
			this.Ramunt.TabStop = true;
			this.Ramunt.Text = "Amount";
			this.Ramunt.UseVisualStyleBackColor = false;
			this.RA.BackColor = global::System.Drawing.Color.LightSteelBlue;
			this.RA.FlatAppearance.BorderSize = 2;
			this.RA.FlatAppearance.CheckedBackColor = global::System.Drawing.Color.Red;
			this.RA.FlatAppearance.MouseDownBackColor = global::System.Drawing.Color.FromArgb(192, 192, 0);
			this.RA.FlatAppearance.MouseOverBackColor = global::System.Drawing.Color.FromArgb(192, 0, 192);
			this.RA.Font = new global::System.Drawing.Font("Arial", 9.75f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.RA.ForeColor = global::System.Drawing.Color.White;
			global::System.Windows.Forms.Control ra = this.RA;
			location = new global::System.Drawing.Point(9, 24);
			ra.Location = location;
			this.RA.Name = "RA";
			global::System.Windows.Forms.Control ra2 = this.RA;
			size = new global::System.Drawing.Size(129, 23);
			ra2.Size = size;
			this.RA.TabIndex = 0;
			this.RA.TabStop = true;
			this.RA.Text = "Name";
			this.RA.UseVisualStyleBackColor = false;
			this.Button1.BackColor = global::System.Drawing.SystemColors.Control;
			this.Button1.Font = new global::System.Drawing.Font("Verdana", 9.75f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Button1.ForeColor = global::System.Drawing.Color.Black;
			global::System.Windows.Forms.Control button = this.Button1;
			location = new global::System.Drawing.Point(15, 369);
			button.Location = location;
			this.Button1.Name = "Button1";
			global::System.Windows.Forms.Control button2 = this.Button1;
			size = new global::System.Drawing.Size(107, 31);
			button2.Size = size;
			this.Button1.TabIndex = 8;
			this.Button1.Text = "Match";
			this.Button1.UseVisualStyleBackColor = false;
			this.GroupBox3.Controls.Add(this.txtsname);
			this.GroupBox3.Controls.Add(this.txtsrun);
			this.GroupBox3.Controls.Add(this.txtsrate);
			this.GroupBox3.Controls.Add(this.txtsamount);
			this.GroupBox3.Controls.Add(this.sessionall);
			this.GroupBox3.Controls.Add(this.Label1);
			this.GroupBox3.Controls.Add(this.SRUN);
			this.GroupBox3.Controls.Add(this.SR);
			this.GroupBox3.Controls.Add(this.SA);
			this.GroupBox3.Controls.Add(this.SN);
			this.GroupBox3.Font = new global::System.Drawing.Font("Arial", 9.75f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.GroupBox3.ForeColor = global::System.Drawing.Color.FromArgb(64, 64, 64);
			global::System.Windows.Forms.Control groupBox3 = this.GroupBox3;
			location = new global::System.Drawing.Point(530, 184);
			groupBox3.Location = location;
			this.GroupBox3.Name = "GroupBox3";
			global::System.Windows.Forms.Control groupBox4 = this.GroupBox3;
			size = new global::System.Drawing.Size(360, 183);
			groupBox4.Size = size;
			this.GroupBox3.TabIndex = 3;
			this.GroupBox3.TabStop = false;
			this.GroupBox3.Text = "Fo Session";
			this.txtsname.DropDownStyle = global::System.Windows.Forms.ComboBoxStyle.Simple;
			this.txtsname.Font = new global::System.Drawing.Font("Arial", 9.75f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.txtsname.FormattingEnabled = true;
			global::System.Windows.Forms.Control txtsname = this.txtsname;
			location = new global::System.Drawing.Point(145, 50);
			txtsname.Location = location;
			this.txtsname.Name = "txtsname";
			global::System.Windows.Forms.Control txtsname2 = this.txtsname;
			size = new global::System.Drawing.Size(207, 24);
			txtsname2.Size = size;
			this.txtsname.TabIndex = 19;
			this.txtsrun.CharacterCasing = global::System.Windows.Forms.CharacterCasing.Upper;
			this.txtsrun.Font = new global::System.Drawing.Font("Arial", 9.75f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			global::System.Windows.Forms.Control txtsrun = this.txtsrun;
			location = new global::System.Drawing.Point(147, 152);
			txtsrun.Location = location;
			this.txtsrun.Name = "txtsrun";
			global::System.Windows.Forms.Control txtsrun2 = this.txtsrun;
			size = new global::System.Drawing.Size(207, 22);
			txtsrun2.Size = size;
			this.txtsrun.TabIndex = 18;
			this.txtsrate.CharacterCasing = global::System.Windows.Forms.CharacterCasing.Upper;
			this.txtsrate.Font = new global::System.Drawing.Font("Arial", 9.75f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			global::System.Windows.Forms.Control txtsrate = this.txtsrate;
			location = new global::System.Drawing.Point(145, 119);
			txtsrate.Location = location;
			this.txtsrate.Name = "txtsrate";
			global::System.Windows.Forms.Control txtsrate2 = this.txtsrate;
			size = new global::System.Drawing.Size(207, 22);
			txtsrate2.Size = size;
			this.txtsrate.TabIndex = 17;
			this.txtsamount.CharacterCasing = global::System.Windows.Forms.CharacterCasing.Upper;
			this.txtsamount.Font = new global::System.Drawing.Font("Arial", 9.75f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			global::System.Windows.Forms.Control txtsamount = this.txtsamount;
			location = new global::System.Drawing.Point(143, 85);
			txtsamount.Location = location;
			this.txtsamount.Name = "txtsamount";
			global::System.Windows.Forms.Control txtsamount2 = this.txtsamount;
			size = new global::System.Drawing.Size(209, 22);
			txtsamount2.Size = size;
			this.txtsamount.TabIndex = 16;
			this.sessionall.DropDownStyle = global::System.Windows.Forms.ComboBoxStyle.DropDownList;
			this.sessionall.Font = new global::System.Drawing.Font("Arial", 9.75f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.sessionall.FormattingEnabled = true;
			global::System.Windows.Forms.Control sessionall = this.sessionall;
			location = new global::System.Drawing.Point(145, 17);
			sessionall.Location = location;
			this.sessionall.Name = "sessionall";
			global::System.Windows.Forms.Control sessionall2 = this.sessionall;
			size = new global::System.Drawing.Size(207, 24);
			sessionall2.Size = size;
			this.sessionall.TabIndex = 10;
			this.Label1.BackColor = global::System.Drawing.Color.LightSteelBlue;
			this.Label1.Font = new global::System.Drawing.Font("Arial", 9.75f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label1.ForeColor = global::System.Drawing.Color.White;
			global::System.Windows.Forms.Control label = this.Label1;
			location = new global::System.Drawing.Point(10, 18);
			label.Location = location;
			this.Label1.Name = "Label1";
			global::System.Windows.Forms.Control label2 = this.Label1;
			size = new global::System.Drawing.Size(129, 23);
			label2.Size = size;
			this.Label1.TabIndex = 9;
			this.Label1.Text = "Select Session";
			this.Label1.TextAlign = global::System.Drawing.ContentAlignment.MiddleCenter;
			this.SRUN.BackColor = global::System.Drawing.Color.LightSteelBlue;
			this.SRUN.FlatAppearance.BorderSize = 2;
			this.SRUN.FlatAppearance.CheckedBackColor = global::System.Drawing.Color.Red;
			this.SRUN.FlatAppearance.MouseDownBackColor = global::System.Drawing.Color.FromArgb(192, 192, 0);
			this.SRUN.FlatAppearance.MouseOverBackColor = global::System.Drawing.Color.FromArgb(192, 0, 192);
			this.SRUN.Font = new global::System.Drawing.Font("Arial", 9.75f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.SRUN.ForeColor = global::System.Drawing.Color.White;
			global::System.Windows.Forms.Control srun = this.SRUN;
			location = new global::System.Drawing.Point(10, 152);
			srun.Location = location;
			this.SRUN.Name = "SRUN";
			global::System.Windows.Forms.Control srun2 = this.SRUN;
			size = new global::System.Drawing.Size(129, 23);
			srun2.Size = size;
			this.SRUN.TabIndex = 3;
			this.SRUN.TabStop = true;
			this.SRUN.Text = "Run";
			this.SRUN.UseVisualStyleBackColor = false;
			this.SR.BackColor = global::System.Drawing.Color.LightSteelBlue;
			this.SR.FlatAppearance.BorderSize = 2;
			this.SR.FlatAppearance.CheckedBackColor = global::System.Drawing.Color.Red;
			this.SR.FlatAppearance.MouseDownBackColor = global::System.Drawing.Color.FromArgb(192, 192, 0);
			this.SR.FlatAppearance.MouseOverBackColor = global::System.Drawing.Color.FromArgb(192, 0, 192);
			this.SR.Font = new global::System.Drawing.Font("Arial", 9.75f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.SR.ForeColor = global::System.Drawing.Color.White;
			global::System.Windows.Forms.Control sr = this.SR;
			location = new global::System.Drawing.Point(10, 119);
			sr.Location = location;
			this.SR.Name = "SR";
			global::System.Windows.Forms.Control sr2 = this.SR;
			size = new global::System.Drawing.Size(129, 23);
			sr2.Size = size;
			this.SR.TabIndex = 2;
			this.SR.TabStop = true;
			this.SR.Text = "Bhav (Rate)";
			this.SR.UseVisualStyleBackColor = false;
			this.SA.BackColor = global::System.Drawing.Color.LightSteelBlue;
			this.SA.FlatAppearance.BorderSize = 2;
			this.SA.FlatAppearance.CheckedBackColor = global::System.Drawing.Color.Red;
			this.SA.FlatAppearance.MouseDownBackColor = global::System.Drawing.Color.FromArgb(192, 192, 0);
			this.SA.FlatAppearance.MouseOverBackColor = global::System.Drawing.Color.FromArgb(192, 0, 192);
			this.SA.Font = new global::System.Drawing.Font("Arial", 9.75f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.SA.ForeColor = global::System.Drawing.Color.White;
			global::System.Windows.Forms.Control sa = this.SA;
			location = new global::System.Drawing.Point(10, 84);
			sa.Location = location;
			this.SA.Name = "SA";
			global::System.Windows.Forms.Control sa2 = this.SA;
			size = new global::System.Drawing.Size(129, 23);
			sa2.Size = size;
			this.SA.TabIndex = 1;
			this.SA.TabStop = true;
			this.SA.Text = "Amount";
			this.SA.UseVisualStyleBackColor = false;
			this.SN.BackColor = global::System.Drawing.Color.LightSteelBlue;
			this.SN.FlatAppearance.BorderSize = 2;
			this.SN.FlatAppearance.CheckedBackColor = global::System.Drawing.Color.Red;
			this.SN.FlatAppearance.MouseDownBackColor = global::System.Drawing.Color.FromArgb(192, 192, 0);
			this.SN.FlatAppearance.MouseOverBackColor = global::System.Drawing.Color.FromArgb(192, 0, 192);
			this.SN.Font = new global::System.Drawing.Font("Arial", 9.75f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.SN.ForeColor = global::System.Drawing.Color.White;
			global::System.Windows.Forms.Control sn = this.SN;
			location = new global::System.Drawing.Point(10, 51);
			sn.Location = location;
			this.SN.Name = "SN";
			global::System.Windows.Forms.Control sn2 = this.SN;
			size = new global::System.Drawing.Size(129, 23);
			sn2.Size = size;
			this.SN.TabIndex = 0;
			this.SN.TabStop = true;
			this.SN.Text = "Name";
			this.SN.UseVisualStyleBackColor = false;
			this.Button2.BackColor = global::System.Drawing.SystemColors.Control;
			this.Button2.Font = new global::System.Drawing.Font("Verdana", 9.75f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Button2.ForeColor = global::System.Drawing.Color.Black;
			global::System.Windows.Forms.Control button3 = this.Button2;
			location = new global::System.Drawing.Point(530, 371);
			button3.Location = location;
			this.Button2.Name = "Button2";
			global::System.Windows.Forms.Control button4 = this.Button2;
			size = new global::System.Drawing.Size(107, 31);
			button4.Size = size;
			this.Button2.TabIndex = 8;
			this.Button2.Text = "Session";
			this.Button2.UseVisualStyleBackColor = false;
			this.Label2.BackColor = global::System.Drawing.Color.LightSteelBlue;
			this.Label2.Dock = global::System.Windows.Forms.DockStyle.Top;
			this.Label2.Font = new global::System.Drawing.Font("Arial", 12f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label2.ForeColor = global::System.Drawing.Color.White;
			global::System.Windows.Forms.Control label3 = this.Label2;
			location = new global::System.Drawing.Point(0, 0);
			label3.Location = location;
			this.Label2.Name = "Label2";
			global::System.Windows.Forms.Control label4 = this.Label2;
			size = new global::System.Drawing.Size(1354, 24);
			label4.Size = size;
			this.Label2.TabIndex = 5;
			this.Label2.Text = "Find Sauda Entry";
			this.Label2.TextAlign = global::System.Drawing.ContentAlignment.MiddleLeft;
			this.Panel1.BorderStyle = global::System.Windows.Forms.BorderStyle.FixedSingle;
			this.Panel1.Controls.Add(this.DataGridView1);
			this.Panel1.Font = new global::System.Drawing.Font("Arial", 9.75f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			global::System.Windows.Forms.Control panel = this.Panel1;
			location = new global::System.Drawing.Point(-1, 27);
			panel.Location = location;
			this.Panel1.Name = "Panel1";
			global::System.Windows.Forms.Control panel2 = this.Panel1;
			size = new global::System.Drawing.Size(891, 157);
			panel2.Size = size;
			this.Panel1.TabIndex = 8;
			this.Panel2.BorderStyle = global::System.Windows.Forms.BorderStyle.FixedSingle;
			this.Panel2.Controls.Add(this.DataGridView3);
			this.Panel2.Controls.Add(this.DataGridView2);
			this.Panel2.Font = new global::System.Drawing.Font("Arial", 9.75f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			global::System.Windows.Forms.Control panel3 = this.Panel2;
			location = new global::System.Drawing.Point(9, 408);
			panel3.Location = location;
			this.Panel2.Name = "Panel2";
			global::System.Windows.Forms.Control panel4 = this.Panel2;
			size = new global::System.Drawing.Size(888, 244);
			panel4.Size = size;
			this.Panel2.TabIndex = 10;
			this.DataGridView3.AllowUserToAddRows = false;
			this.DataGridView3.AllowUserToDeleteRows = false;
			this.DataGridView3.AllowUserToOrderColumns = true;
			this.DataGridView3.AllowUserToResizeColumns = false;
			this.DataGridView3.AllowUserToResizeRows = false;
			this.DataGridView3.BackgroundColor = global::System.Drawing.Color.White;
			this.DataGridView3.BorderStyle = global::System.Windows.Forms.BorderStyle.None;
			this.DataGridView3.ColumnHeadersBorderStyle = global::System.Windows.Forms.DataGridViewHeaderBorderStyle.Single;
			dataGridViewCellStyle2.Alignment = global::System.Windows.Forms.DataGridViewContentAlignment.MiddleCenter;
			dataGridViewCellStyle2.BackColor = global::System.Drawing.Color.LightSteelBlue;
			dataGridViewCellStyle2.Font = new global::System.Drawing.Font("Arial", 9.75f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			dataGridViewCellStyle2.ForeColor = global::System.Drawing.Color.White;
			dataGridViewCellStyle2.SelectionBackColor = global::System.Drawing.Color.LightSteelBlue;
			dataGridViewCellStyle2.SelectionForeColor = global::System.Drawing.Color.White;
			dataGridViewCellStyle2.WrapMode = global::System.Windows.Forms.DataGridViewTriState.True;
			this.DataGridView3.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle2;
			this.DataGridView3.ColumnHeadersHeightSizeMode = global::System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.AutoSize;
			this.DataGridView3.Columns.AddRange(new global::System.Windows.Forms.DataGridViewColumn[]
			{
				this.DataGridViewTextBoxColumn1,
				this.DataGridViewTextBoxColumn2,
				this.DataGridViewTextBoxColumn3,
				this.DataGridViewTextBoxColumn4,
				this.DataGridViewTextBoxColumn5,
				this.DataGridViewTextBoxColumn6,
				this.DataGridViewTextBoxColumn7,
				this.DataGridViewTextBoxColumn8,
				this.DataGridViewTextBoxColumn9,
				this.DataGridViewTextBoxColumn10,
				this.DataGridViewTextBoxColumn11
			});
			dataGridViewCellStyle3.Alignment = global::System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
			dataGridViewCellStyle3.BackColor = global::System.Drawing.SystemColors.Window;
			dataGridViewCellStyle3.Font = new global::System.Drawing.Font("Arial", 9.75f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			dataGridViewCellStyle3.ForeColor = global::System.Drawing.SystemColors.ControlText;
			dataGridViewCellStyle3.SelectionBackColor = global::System.Drawing.Color.DeepSkyBlue;
			dataGridViewCellStyle3.SelectionForeColor = global::System.Drawing.Color.White;
			dataGridViewCellStyle3.WrapMode = global::System.Windows.Forms.DataGridViewTriState.False;
			this.DataGridView3.DefaultCellStyle = dataGridViewCellStyle3;
			this.DataGridView3.EnableHeadersVisualStyles = false;
			this.DataGridView3.GridColor = global::System.Drawing.SystemColors.Control;
			global::System.Windows.Forms.Control dataGridView3 = this.DataGridView3;
			location = new global::System.Drawing.Point(0, 77);
			dataGridView3.Location = location;
			this.DataGridView3.MultiSelect = false;
			this.DataGridView3.Name = "DataGridView3";
			this.DataGridView3.ReadOnly = true;
			this.DataGridView3.RowHeadersVisible = false;
			this.DataGridView3.SelectionMode = global::System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
			global::System.Windows.Forms.Control dataGridView4 = this.DataGridView3;
			size = new global::System.Drawing.Size(891, 165);
			dataGridView4.Size = size;
			this.DataGridView3.TabIndex = 22;
			this.DataGridViewTextBoxColumn1.HeaderText = "Sr_No";
			this.DataGridViewTextBoxColumn1.Name = "DataGridViewTextBoxColumn1";
			this.DataGridViewTextBoxColumn1.ReadOnly = true;
			this.DataGridViewTextBoxColumn1.Width = 50;
			this.DataGridViewTextBoxColumn2.HeaderText = "Run";
			this.DataGridViewTextBoxColumn2.Name = "DataGridViewTextBoxColumn2";
			this.DataGridViewTextBoxColumn2.ReadOnly = true;
			this.DataGridViewTextBoxColumn2.Width = 70;
			this.DataGridViewTextBoxColumn3.HeaderText = "Amount";
			this.DataGridViewTextBoxColumn3.Name = "DataGridViewTextBoxColumn3";
			this.DataGridViewTextBoxColumn3.ReadOnly = true;
			this.DataGridViewTextBoxColumn3.Width = 90;
			this.DataGridViewTextBoxColumn4.HeaderText = "Rate";
			this.DataGridViewTextBoxColumn4.Name = "DataGridViewTextBoxColumn4";
			this.DataGridViewTextBoxColumn4.ReadOnly = true;
			this.DataGridViewTextBoxColumn4.Width = 70;
			this.DataGridViewTextBoxColumn5.HeaderText = "Badli";
			this.DataGridViewTextBoxColumn5.Name = "DataGridViewTextBoxColumn5";
			this.DataGridViewTextBoxColumn5.ReadOnly = true;
			this.DataGridViewTextBoxColumn5.Width = 60;
			this.DataGridViewTextBoxColumn6.HeaderText = "Mode";
			this.DataGridViewTextBoxColumn6.Name = "DataGridViewTextBoxColumn6";
			this.DataGridViewTextBoxColumn6.ReadOnly = true;
			this.DataGridViewTextBoxColumn6.Width = 50;
			this.DataGridViewTextBoxColumn7.HeaderText = "Party";
			this.DataGridViewTextBoxColumn7.Name = "DataGridViewTextBoxColumn7";
			this.DataGridViewTextBoxColumn7.ReadOnly = true;
			this.DataGridViewTextBoxColumn8.HeaderText = "Yes";
			this.DataGridViewTextBoxColumn8.Name = "DataGridViewTextBoxColumn8";
			this.DataGridViewTextBoxColumn8.ReadOnly = true;
			this.DataGridViewTextBoxColumn9.HeaderText = "No";
			this.DataGridViewTextBoxColumn9.Name = "DataGridViewTextBoxColumn9";
			this.DataGridViewTextBoxColumn9.ReadOnly = true;
			dataGridViewCellStyle4.Format = "d";
			dataGridViewCellStyle4.NullValue = null;
			this.DataGridViewTextBoxColumn10.DefaultCellStyle = dataGridViewCellStyle4;
			this.DataGridViewTextBoxColumn10.HeaderText = "Time";
			this.DataGridViewTextBoxColumn10.Name = "DataGridViewTextBoxColumn10";
			this.DataGridViewTextBoxColumn10.ReadOnly = true;
			this.DataGridViewTextBoxColumn11.HeaderText = "Page";
			this.DataGridViewTextBoxColumn11.Name = "DataGridViewTextBoxColumn11";
			this.DataGridViewTextBoxColumn11.ReadOnly = true;
			this.DataGridViewTextBoxColumn11.Width = 40;
			this.DataGridView2.BackgroundColor = global::System.Drawing.Color.White;
			dataGridViewCellStyle5.Alignment = global::System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
			dataGridViewCellStyle5.BackColor = global::System.Drawing.Color.LightSteelBlue;
			dataGridViewCellStyle5.Font = new global::System.Drawing.Font("Arial", 9.75f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			dataGridViewCellStyle5.ForeColor = global::System.Drawing.Color.White;
			dataGridViewCellStyle5.SelectionBackColor = global::System.Drawing.Color.LightSteelBlue;
			dataGridViewCellStyle5.SelectionForeColor = global::System.Drawing.Color.White;
			dataGridViewCellStyle5.WrapMode = global::System.Windows.Forms.DataGridViewTriState.True;
			this.DataGridView2.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle5;
			this.DataGridView2.Columns.AddRange(new global::System.Windows.Forms.DataGridViewColumn[]
			{
				this.Column7,
				this.Column8,
				this.Column9,
				this.Column10,
				this.Column11,
				this.Column12,
				this.Column13,
				this.Column14,
				this.Column15,
				this.Column16,
				this.Column17,
				this.Column18,
				this.Column19
			});
			dataGridViewCellStyle6.Alignment = global::System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
			dataGridViewCellStyle6.BackColor = global::System.Drawing.SystemColors.Window;
			dataGridViewCellStyle6.Font = new global::System.Drawing.Font("Arial", 9.75f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			dataGridViewCellStyle6.ForeColor = global::System.Drawing.SystemColors.ControlText;
			dataGridViewCellStyle6.SelectionBackColor = global::System.Drawing.Color.DeepSkyBlue;
			dataGridViewCellStyle6.SelectionForeColor = global::System.Drawing.SystemColors.HighlightText;
			dataGridViewCellStyle6.WrapMode = global::System.Windows.Forms.DataGridViewTriState.False;
			this.DataGridView2.DefaultCellStyle = dataGridViewCellStyle6;
			this.DataGridView2.Dock = global::System.Windows.Forms.DockStyle.Fill;
			this.DataGridView2.EnableHeadersVisualStyles = false;
			this.DataGridView2.GridColor = global::System.Drawing.SystemColors.Control;
			global::System.Windows.Forms.Control dataGridView5 = this.DataGridView2;
			location = new global::System.Drawing.Point(0, 0);
			dataGridView5.Location = location;
			this.DataGridView2.Name = "DataGridView2";
			this.DataGridView2.ReadOnly = true;
			this.DataGridView2.RowHeadersVisible = false;
			global::System.Windows.Forms.Control dataGridView6 = this.DataGridView2;
			size = new global::System.Drawing.Size(886, 242);
			dataGridView6.Size = size;
			this.DataGridView2.TabIndex = 0;
			dataGridViewCellStyle7.Format = "N0";
			dataGridViewCellStyle7.NullValue = null;
			this.Column7.DefaultCellStyle = dataGridViewCellStyle7;
			this.Column7.HeaderText = "Sr_No";
			this.Column7.Name = "Column7";
			this.Column7.ReadOnly = true;
			this.Column7.Width = 50;
			this.Column8.HeaderText = "Party_Name";
			this.Column8.Name = "Column8";
			this.Column8.ReadOnly = true;
			this.Column8.Width = 120;
			this.Column9.HeaderText = "Amount";
			this.Column9.Name = "Column9";
			this.Column9.ReadOnly = true;
			this.Column10.HeaderText = "Rate";
			this.Column10.Name = "Column10";
			this.Column10.ReadOnly = true;
			this.Column11.HeaderText = "Fovrt";
			this.Column11.Name = "Column11";
			this.Column11.ReadOnly = true;
			this.Column12.HeaderText = "Mode";
			this.Column12.Name = "Column12";
			this.Column12.ReadOnly = true;
			this.Column13.HeaderText = "";
			this.Column13.Name = "Column13";
			this.Column13.ReadOnly = true;
			this.Column14.HeaderText = "";
			this.Column14.Name = "Column14";
			this.Column14.ReadOnly = true;
			this.Column15.HeaderText = "";
			this.Column15.Name = "Column15";
			this.Column15.ReadOnly = true;
			this.Column16.HeaderText = "";
			this.Column16.Name = "Column16";
			this.Column16.ReadOnly = true;
			this.Column17.HeaderText = "Time";
			this.Column17.Name = "Column17";
			this.Column17.ReadOnly = true;
			this.Column18.HeaderText = "Page _No";
			this.Column18.Name = "Column18";
			this.Column18.ReadOnly = true;
			this.Column18.Width = 50;
			this.Column19.HeaderText = "Date";
			this.Column19.Name = "Column19";
			this.Column19.ReadOnly = true;
			global::System.Windows.Forms.Control testnu = this.testnu;
			location = new global::System.Drawing.Point(1100, 176);
			testnu.Location = location;
			this.testnu.Name = "testnu";
			global::System.Windows.Forms.Control testnu2 = this.testnu;
			size = new global::System.Drawing.Size(26, 25);
			testnu2.Size = size;
			this.testnu.TabIndex = 11;
			this.Button3.BackColor = global::System.Drawing.Color.FromArgb(192, 0, 0);
			this.Button3.DialogResult = global::System.Windows.Forms.DialogResult.Cancel;
			this.Button3.Font = new global::System.Drawing.Font("Verdana", 9.75f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Button3.ForeColor = global::System.Drawing.Color.White;
			global::System.Windows.Forms.Control button5 = this.Button3;
			location = new global::System.Drawing.Point(781, 370);
			button5.Location = location;
			this.Button3.Name = "Button3";
			global::System.Windows.Forms.Control button6 = this.Button3;
			size = new global::System.Drawing.Size(109, 31);
			button6.Size = size;
			this.Button3.TabIndex = 12;
			this.Button3.Text = "Exit";
			this.Button3.UseVisualStyleBackColor = false;
			global::System.Windows.Forms.Control txtnu = this.txtnu;
			location = new global::System.Drawing.Point(1081, 64);
			txtnu.Location = location;
			this.txtnu.Name = "txtnu";
			global::System.Windows.Forms.Control txtnu2 = this.txtnu;
			size = new global::System.Drawing.Size(100, 25);
			txtnu2.Size = size;
			this.txtnu.TabIndex = 13;
			this.txtnu.Text = ".000";
			this.txtsid.FormattingEnabled = true;
			global::System.Windows.Forms.Control txtsid = this.txtsid;
			location = new global::System.Drawing.Point(1088, 133);
			txtsid.Location = location;
			this.txtsid.Name = "txtsid";
			global::System.Windows.Forms.Control txtsid2 = this.txtsid;
			size = new global::System.Drawing.Size(121, 25);
			txtsid2.Size = size;
			this.txtsid.TabIndex = 14;
			global::System.Windows.Forms.Control panel5 = this.Panel3;
			location = new global::System.Drawing.Point(1009, 52);
			panel5.Location = location;
			this.Panel3.Name = "Panel3";
			global::System.Windows.Forms.Control panel6 = this.Panel3;
			size = new global::System.Drawing.Size(200, 263);
			panel6.Size = size;
			this.Panel3.TabIndex = 15;
			global::System.Drawing.SizeF autoScaleDimensions = new global::System.Drawing.SizeF(8f, 17f);
			this.AutoScaleDimensions = autoScaleDimensions;
			this.AutoScaleMode = global::System.Windows.Forms.AutoScaleMode.Font;
			this.CancelButton = this.Button3;
			size = new global::System.Drawing.Size(1354, 733);
			this.ClientSize = size;
			this.ControlBox = false;
			this.Controls.Add(this.Panel3);
			this.Controls.Add(this.txtsid);
			this.Controls.Add(this.txtnu);
			this.Controls.Add(this.Button3);
			this.Controls.Add(this.testnu);
			this.Controls.Add(this.Panel2);
			this.Controls.Add(this.Button1);
			this.Controls.Add(this.Panel1);
			this.Controls.Add(this.Label2);
			this.Controls.Add(this.Button2);
			this.Controls.Add(this.GroupBox3);
			this.Controls.Add(this.GroupBox2);
			this.Font = new global::System.Drawing.Font("Segoe UI Semibold", 9.75f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			global::System.Windows.Forms.Padding margin = new global::System.Windows.Forms.Padding(4);
			this.Margin = margin;
			this.Name = "Find_Sauda_Entry";
			this.ShowIcon = false;
			this.ShowInTaskbar = false;
			this.SizeGripStyle = global::System.Windows.Forms.SizeGripStyle.Hide;
			this.Text = "Find_Sauda_Entry";
			this.WindowState = global::System.Windows.Forms.FormWindowState.Maximized;
			((global::System.ComponentModel.ISupportInitialize)this.DataGridView1).EndInit();
			this.GroupBox2.ResumeLayout(false);
			this.GroupBox2.PerformLayout();
			this.GroupBox3.ResumeLayout(false);
			this.GroupBox3.PerformLayout();
			this.Panel1.ResumeLayout(false);
			this.Panel2.ResumeLayout(false);
			((global::System.ComponentModel.ISupportInitialize)this.DataGridView3).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.DataGridView2).EndInit();
			this.ResumeLayout(false);
			this.PerformLayout();
		}

		// Token: 0x0400052D RID: 1325
		private global::System.ComponentModel.IContainer components;
	}
}
