namespace YashAksh
{
	// Token: 0x02000040 RID: 64
	[global::Microsoft.VisualBasic.CompilerServices.DesignerGenerated]
	public partial class Frm_FinalSudaEntry : global::System.Windows.Forms.Form
	{
		// Token: 0x06000C85 RID: 3205 RVA: 0x00306A28 File Offset: 0x00304E28
		[global::System.Diagnostics.DebuggerNonUserCode]
		protected override void Dispose(bool disposing)
		{
			try
			{
				if (disposing && this.components != null)
				{
					this.components.Dispose();
				}
			}
			finally
			{
				base.Dispose(disposing);
			}
		}

		// Token: 0x06000C86 RID: 3206 RVA: 0x00306A68 File Offset: 0x00304E68
		[global::System.Diagnostics.DebuggerStepThrough]
		private void InitializeComponent()
		{
			global::System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle = new global::System.Windows.Forms.DataGridViewCellStyle();
			global::System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle2 = new global::System.Windows.Forms.DataGridViewCellStyle();
			global::System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle3 = new global::System.Windows.Forms.DataGridViewCellStyle();
			global::System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle4 = new global::System.Windows.Forms.DataGridViewCellStyle();
			global::System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle5 = new global::System.Windows.Forms.DataGridViewCellStyle();
			this.Panel1 = new global::System.Windows.Forms.Panel();
			this.SplitContainer1 = new global::System.Windows.Forms.SplitContainer();
			this.DataGridView1 = new global::System.Windows.Forms.DataGridView();
			this.Label1 = new global::System.Windows.Forms.Label();
			this.txtnu = new global::System.Windows.Forms.TextBox();
			this.CheckBox2 = new global::System.Windows.Forms.CheckBox();
			this.comsesstionID = new global::System.Windows.Forms.ComboBox();
			this.lblmatchID = new global::System.Windows.Forms.Label();
			this.Button3 = new global::System.Windows.Forms.Button();
			this.Button2 = new global::System.Windows.Forms.Button();
			this.Button1 = new global::System.Windows.Forms.Button();
			this.GroupBox3 = new global::System.Windows.Forms.GroupBox();
			this.CheckBox1 = new global::System.Windows.Forms.CheckBox();
			this.txtsname = new global::System.Windows.Forms.ComboBox();
			this.txtsrun = new global::System.Windows.Forms.TextBox();
			this.txtsrate = new global::System.Windows.Forms.TextBox();
			this.txtsamount = new global::System.Windows.Forms.TextBox();
			this.sessionall = new global::System.Windows.Forms.ComboBox();
			this.SRUN = new global::System.Windows.Forms.RadioButton();
			this.SR = new global::System.Windows.Forms.RadioButton();
			this.SA = new global::System.Windows.Forms.RadioButton();
			this.SN = new global::System.Windows.Forms.RadioButton();
			this.GroupBox2 = new global::System.Windows.Forms.GroupBox();
			this.txtteam = new global::System.Windows.Forms.TextBox();
			this.txtrate = new global::System.Windows.Forms.TextBox();
			this.txtamount = new global::System.Windows.Forms.TextBox();
			this.txtname = new global::System.Windows.Forms.ComboBox();
			this.Rteam = new global::System.Windows.Forms.RadioButton();
			this.Rrate = new global::System.Windows.Forms.RadioButton();
			this.Ramunt = new global::System.Windows.Forms.RadioButton();
			this.RA = new global::System.Windows.Forms.RadioButton();
			this.Label2 = new global::System.Windows.Forms.Label();
			this.Panel2 = new global::System.Windows.Forms.Panel();
			this.SplitContainer2 = new global::System.Windows.Forms.SplitContainer();
			this.DataGridView2 = new global::System.Windows.Forms.DataGridView();
			this.DataGridView3 = new global::System.Windows.Forms.DataGridView();
			this.Panel1.SuspendLayout();
			this.SplitContainer1.Panel1.SuspendLayout();
			this.SplitContainer1.Panel2.SuspendLayout();
			this.SplitContainer1.SuspendLayout();
			((global::System.ComponentModel.ISupportInitialize)this.DataGridView1).BeginInit();
			this.GroupBox3.SuspendLayout();
			this.GroupBox2.SuspendLayout();
			this.Panel2.SuspendLayout();
			this.SplitContainer2.Panel1.SuspendLayout();
			this.SplitContainer2.Panel2.SuspendLayout();
			this.SplitContainer2.SuspendLayout();
			((global::System.ComponentModel.ISupportInitialize)this.DataGridView2).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.DataGridView3).BeginInit();
			this.SuspendLayout();
			this.Panel1.BorderStyle = global::System.Windows.Forms.BorderStyle.FixedSingle;
			this.Panel1.Controls.Add(this.SplitContainer1);
			this.Panel1.Dock = global::System.Windows.Forms.DockStyle.Top;
			global::System.Windows.Forms.Control panel = this.Panel1;
			global::System.Drawing.Point location = new global::System.Drawing.Point(0, 0);
			panel.Location = location;
			this.Panel1.Name = "Panel1";
			global::System.Windows.Forms.Control panel2 = this.Panel1;
			global::System.Drawing.Size size = new global::System.Drawing.Size(1354, 245);
			panel2.Size = size;
			this.Panel1.TabIndex = 0;
			this.SplitContainer1.BackColor = global::System.Drawing.Color.White;
			this.SplitContainer1.Dock = global::System.Windows.Forms.DockStyle.Fill;
			global::System.Windows.Forms.Control splitContainer = this.SplitContainer1;
			location = new global::System.Drawing.Point(0, 0);
			splitContainer.Location = location;
			this.SplitContainer1.Name = "SplitContainer1";
			this.SplitContainer1.Panel1.Controls.Add(this.DataGridView1);
			this.SplitContainer1.Panel1.Controls.Add(this.Label1);
			this.SplitContainer1.Panel1.Font = new global::System.Drawing.Font("Verdana", 9.75f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.SplitContainer1.Panel2.BackColor = global::System.Drawing.Color.Lavender;
			this.SplitContainer1.Panel2.Controls.Add(this.txtnu);
			this.SplitContainer1.Panel2.Controls.Add(this.CheckBox2);
			this.SplitContainer1.Panel2.Controls.Add(this.comsesstionID);
			this.SplitContainer1.Panel2.Controls.Add(this.lblmatchID);
			this.SplitContainer1.Panel2.Controls.Add(this.Button3);
			this.SplitContainer1.Panel2.Controls.Add(this.Button2);
			this.SplitContainer1.Panel2.Controls.Add(this.Button1);
			this.SplitContainer1.Panel2.Controls.Add(this.GroupBox3);
			this.SplitContainer1.Panel2.Controls.Add(this.GroupBox2);
			this.SplitContainer1.Panel2.Controls.Add(this.Label2);
			global::System.Windows.Forms.Control splitContainer2 = this.SplitContainer1;
			size = new global::System.Drawing.Size(1352, 243);
			splitContainer2.Size = size;
			this.SplitContainer1.SplitterDistance = 694;
			this.SplitContainer1.TabIndex = 0;
			this.DataGridView1.AutoSizeColumnsMode = global::System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
			this.DataGridView1.AutoSizeRowsMode = global::System.Windows.Forms.DataGridViewAutoSizeRowsMode.DisplayedCells;
			this.DataGridView1.BackgroundColor = global::System.Drawing.SystemColors.Control;
			this.DataGridView1.BorderStyle = global::System.Windows.Forms.BorderStyle.None;
			dataGridViewCellStyle.Alignment = global::System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
			dataGridViewCellStyle.BackColor = global::System.Drawing.Color.SpringGreen;
			dataGridViewCellStyle.Font = new global::System.Drawing.Font("Verdana", 9.75f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			dataGridViewCellStyle.ForeColor = global::System.Drawing.Color.FromArgb(64, 64, 64);
			dataGridViewCellStyle.SelectionBackColor = global::System.Drawing.SystemColors.Highlight;
			dataGridViewCellStyle.SelectionForeColor = global::System.Drawing.SystemColors.HighlightText;
			dataGridViewCellStyle.WrapMode = global::System.Windows.Forms.DataGridViewTriState.True;
			this.DataGridView1.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle;
			this.DataGridView1.Dock = global::System.Windows.Forms.DockStyle.Fill;
			this.DataGridView1.EnableHeadersVisualStyles = false;
			this.DataGridView1.GridColor = global::System.Drawing.Color.Gainsboro;
			global::System.Windows.Forms.Control dataGridView = this.DataGridView1;
			location = new global::System.Drawing.Point(0, 18);
			dataGridView.Location = location;
			this.DataGridView1.MultiSelect = false;
			this.DataGridView1.Name = "DataGridView1";
			this.DataGridView1.ReadOnly = true;
			this.DataGridView1.RowHeadersVisible = false;
			this.DataGridView1.RowHeadersWidthSizeMode = global::System.Windows.Forms.DataGridViewRowHeadersWidthSizeMode.DisableResizing;
			this.DataGridView1.RowTemplate.ReadOnly = true;
			this.DataGridView1.SelectionMode = global::System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
			global::System.Windows.Forms.Control dataGridView2 = this.DataGridView1;
			size = new global::System.Drawing.Size(694, 225);
			dataGridView2.Size = size;
			this.DataGridView1.TabIndex = 1;
			this.Label1.BackColor = global::System.Drawing.Color.FromArgb(0, 192, 192);
			this.Label1.BorderStyle = global::System.Windows.Forms.BorderStyle.FixedSingle;
			this.Label1.Dock = global::System.Windows.Forms.DockStyle.Top;
			this.Label1.FlatStyle = global::System.Windows.Forms.FlatStyle.Popup;
			this.Label1.Font = new global::System.Drawing.Font("Verdana", 9.75f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label1.ForeColor = global::System.Drawing.Color.White;
			global::System.Windows.Forms.Control label = this.Label1;
			location = new global::System.Drawing.Point(0, 0);
			label.Location = location;
			this.Label1.Name = "Label1";
			global::System.Windows.Forms.Control label2 = this.Label1;
			size = new global::System.Drawing.Size(694, 18);
			label2.Size = size;
			this.Label1.TabIndex = 0;
			this.Label1.Text = "ALL MATCHS";
			this.Label1.TextAlign = global::System.Drawing.ContentAlignment.MiddleCenter;
			global::System.Windows.Forms.Control txtnu = this.txtnu;
			location = new global::System.Drawing.Point(518, 215);
			txtnu.Location = location;
			this.txtnu.Name = "txtnu";
			global::System.Windows.Forms.Control txtnu2 = this.txtnu;
			size = new global::System.Drawing.Size(100, 23);
			txtnu2.Size = size;
			this.txtnu.TabIndex = 11;
			this.CheckBox2.AutoSize = true;
			global::System.Windows.Forms.Control checkBox = this.CheckBox2;
			location = new global::System.Drawing.Point(520, 171);
			checkBox.Location = location;
			this.CheckBox2.Name = "CheckBox2";
			global::System.Windows.Forms.Control checkBox2 = this.CheckBox2;
			size = new global::System.Drawing.Size(98, 20);
			checkBox2.Size = size;
			this.CheckBox2.TabIndex = 10;
			this.CheckBox2.Text = "CheckBox2";
			this.CheckBox2.UseVisualStyleBackColor = true;
			this.comsesstionID.FormattingEnabled = true;
			global::System.Windows.Forms.Control comsesstionID = this.comsesstionID;
			location = new global::System.Drawing.Point(489, 108);
			comsesstionID.Location = location;
			this.comsesstionID.Name = "comsesstionID";
			global::System.Windows.Forms.Control comsesstionID2 = this.comsesstionID;
			size = new global::System.Drawing.Size(121, 24);
			comsesstionID2.Size = size;
			this.comsesstionID.TabIndex = 9;
			this.lblmatchID.AutoSize = true;
			global::System.Windows.Forms.Control lblmatchID = this.lblmatchID;
			location = new global::System.Drawing.Point(513, 37);
			lblmatchID.Location = location;
			this.lblmatchID.Name = "lblmatchID";
			global::System.Windows.Forms.Control lblmatchID2 = this.lblmatchID;
			size = new global::System.Drawing.Size(0, 16);
			lblmatchID2.Size = size;
			this.lblmatchID.TabIndex = 8;
			this.Button3.BackColor = global::System.Drawing.Color.Red;
			this.Button3.FlatStyle = global::System.Windows.Forms.FlatStyle.Popup;
			this.Button3.Font = new global::System.Drawing.Font("Verdana", 9.75f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Button3.ForeColor = global::System.Drawing.Color.White;
			global::System.Windows.Forms.Control button = this.Button3;
			location = new global::System.Drawing.Point(386, 202);
			button.Location = location;
			this.Button3.Name = "Button3";
			global::System.Windows.Forms.Control button2 = this.Button3;
			size = new global::System.Drawing.Size(97, 34);
			button2.Size = size;
			this.Button3.TabIndex = 7;
			this.Button3.Text = "&Exit";
			this.Button3.UseVisualStyleBackColor = false;
			this.Button2.BackColor = global::System.Drawing.Color.FromArgb(255, 128, 255);
			this.Button2.FlatStyle = global::System.Windows.Forms.FlatStyle.Popup;
			this.Button2.Font = new global::System.Drawing.Font("Verdana", 9.75f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Button2.ForeColor = global::System.Drawing.Color.White;
			global::System.Windows.Forms.Control button3 = this.Button2;
			location = new global::System.Drawing.Point(210, 202);
			button3.Location = location;
			this.Button2.Name = "Button2";
			global::System.Windows.Forms.Control button4 = this.Button2;
			size = new global::System.Drawing.Size(97, 34);
			button4.Size = size;
			this.Button2.TabIndex = 6;
			this.Button2.Text = "Session";
			this.Button2.UseVisualStyleBackColor = false;
			this.Button1.BackColor = global::System.Drawing.Color.FromArgb(128, 128, 255);
			this.Button1.FlatStyle = global::System.Windows.Forms.FlatStyle.Popup;
			this.Button1.Font = new global::System.Drawing.Font("Verdana", 9.75f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Button1.ForeColor = global::System.Drawing.Color.White;
			global::System.Windows.Forms.Control button5 = this.Button1;
			location = new global::System.Drawing.Point(17, 202);
			button5.Location = location;
			this.Button1.Name = "Button1";
			global::System.Windows.Forms.Control button6 = this.Button1;
			size = new global::System.Drawing.Size(97, 34);
			button6.Size = size;
			this.Button1.TabIndex = 5;
			this.Button1.Text = "Match ";
			this.Button1.UseVisualStyleBackColor = false;
			this.GroupBox3.Controls.Add(this.CheckBox1);
			this.GroupBox3.Controls.Add(this.txtsname);
			this.GroupBox3.Controls.Add(this.txtsrun);
			this.GroupBox3.Controls.Add(this.txtsrate);
			this.GroupBox3.Controls.Add(this.txtsamount);
			this.GroupBox3.Controls.Add(this.sessionall);
			this.GroupBox3.Controls.Add(this.SRUN);
			this.GroupBox3.Controls.Add(this.SR);
			this.GroupBox3.Controls.Add(this.SA);
			this.GroupBox3.Controls.Add(this.SN);
			this.GroupBox3.Font = new global::System.Drawing.Font("Verdana", 9.75f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.GroupBox3.ForeColor = global::System.Drawing.Color.LimeGreen;
			global::System.Windows.Forms.Control groupBox = this.GroupBox3;
			location = new global::System.Drawing.Point(3, 97);
			groupBox.Location = location;
			this.GroupBox3.Name = "GroupBox3";
			global::System.Windows.Forms.Control groupBox2 = this.GroupBox3;
			size = new global::System.Drawing.Size(480, 99);
			groupBox2.Size = size;
			this.GroupBox3.TabIndex = 4;
			this.GroupBox3.TabStop = false;
			this.CheckBox1.AutoSize = true;
			this.CheckBox1.BackColor = global::System.Drawing.Color.SteelBlue;
			this.CheckBox1.Font = new global::System.Drawing.Font("Verdana", 9f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.CheckBox1.ForeColor = global::System.Drawing.Color.White;
			global::System.Windows.Forms.Control checkBox3 = this.CheckBox1;
			location = new global::System.Drawing.Point(9, 14);
			checkBox3.Location = location;
			this.CheckBox1.Name = "CheckBox1";
			global::System.Windows.Forms.Control checkBox4 = this.CheckBox1;
			size = new global::System.Drawing.Size(180, 18);
			checkBox4.Size = size;
			this.CheckBox1.TabIndex = 20;
			this.CheckBox1.Text = "SELECT ALL SESSIONS";
			this.CheckBox1.UseVisualStyleBackColor = false;
			this.txtsname.BackColor = global::System.Drawing.Color.FromArgb(192, 255, 192);
			this.txtsname.DropDownStyle = global::System.Windows.Forms.ComboBoxStyle.Simple;
			this.txtsname.Font = new global::System.Drawing.Font("Arial", 9.75f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.txtsname.FormattingEnabled = true;
			global::System.Windows.Forms.Control txtsname = this.txtsname;
			location = new global::System.Drawing.Point(115, 40);
			txtsname.Location = location;
			this.txtsname.Name = "txtsname";
			global::System.Windows.Forms.Control txtsname2 = this.txtsname;
			size = new global::System.Drawing.Size(152, 24);
			txtsname2.Size = size;
			this.txtsname.TabIndex = 19;
			this.txtsrun.BackColor = global::System.Drawing.Color.FromArgb(192, 255, 192);
			this.txtsrun.CharacterCasing = global::System.Windows.Forms.CharacterCasing.Upper;
			this.txtsrun.Font = new global::System.Drawing.Font("Arial", 9.75f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			global::System.Windows.Forms.Control txtsrun = this.txtsrun;
			location = new global::System.Drawing.Point(365, 69);
			txtsrun.Location = location;
			this.txtsrun.Name = "txtsrun";
			global::System.Windows.Forms.Control txtsrun2 = this.txtsrun;
			size = new global::System.Drawing.Size(101, 22);
			txtsrun2.Size = size;
			this.txtsrun.TabIndex = 18;
			this.txtsrate.BackColor = global::System.Drawing.Color.FromArgb(192, 255, 192);
			this.txtsrate.CharacterCasing = global::System.Windows.Forms.CharacterCasing.Upper;
			this.txtsrate.Font = new global::System.Drawing.Font("Arial", 9.75f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			global::System.Windows.Forms.Control txtsrate = this.txtsrate;
			location = new global::System.Drawing.Point(115, 70);
			txtsrate.Location = location;
			this.txtsrate.Name = "txtsrate";
			global::System.Windows.Forms.Control txtsrate2 = this.txtsrate;
			size = new global::System.Drawing.Size(152, 22);
			txtsrate2.Size = size;
			this.txtsrate.TabIndex = 17;
			this.txtsamount.BackColor = global::System.Drawing.Color.FromArgb(192, 255, 192);
			this.txtsamount.CharacterCasing = global::System.Windows.Forms.CharacterCasing.Upper;
			this.txtsamount.Font = new global::System.Drawing.Font("Arial", 9.75f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			global::System.Windows.Forms.Control txtsamount = this.txtsamount;
			location = new global::System.Drawing.Point(365, 40);
			txtsamount.Location = location;
			this.txtsamount.Name = "txtsamount";
			global::System.Windows.Forms.Control txtsamount2 = this.txtsamount;
			size = new global::System.Drawing.Size(101, 22);
			txtsamount2.Size = size;
			this.txtsamount.TabIndex = 16;
			this.sessionall.DropDownStyle = global::System.Windows.Forms.ComboBoxStyle.DropDownList;
			this.sessionall.Font = new global::System.Drawing.Font("Arial", 9.75f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.sessionall.FormattingEnabled = true;
			global::System.Windows.Forms.Control sessionall = this.sessionall;
			location = new global::System.Drawing.Point(273, 11);
			sessionall.Location = location;
			this.sessionall.Name = "sessionall";
			global::System.Windows.Forms.Control sessionall2 = this.sessionall;
			size = new global::System.Drawing.Size(193, 24);
			sessionall2.Size = size;
			this.sessionall.TabIndex = 10;
			this.SRUN.BackColor = global::System.Drawing.Color.FromArgb(192, 192, 0);
			this.SRUN.FlatAppearance.BorderSize = 2;
			this.SRUN.FlatAppearance.CheckedBackColor = global::System.Drawing.Color.Red;
			this.SRUN.FlatAppearance.MouseDownBackColor = global::System.Drawing.Color.FromArgb(192, 192, 0);
			this.SRUN.FlatAppearance.MouseOverBackColor = global::System.Drawing.Color.FromArgb(192, 0, 192);
			this.SRUN.Font = new global::System.Drawing.Font("Arial", 9.75f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.SRUN.ForeColor = global::System.Drawing.Color.White;
			global::System.Windows.Forms.Control srun = this.SRUN;
			location = new global::System.Drawing.Point(273, 69);
			srun.Location = location;
			this.SRUN.Name = "SRUN";
			global::System.Windows.Forms.Control srun2 = this.SRUN;
			size = new global::System.Drawing.Size(89, 23);
			srun2.Size = size;
			this.SRUN.TabIndex = 3;
			this.SRUN.TabStop = true;
			this.SRUN.Text = "Run";
			this.SRUN.UseVisualStyleBackColor = false;
			this.SR.BackColor = global::System.Drawing.Color.FromArgb(192, 192, 0);
			this.SR.FlatAppearance.BorderSize = 2;
			this.SR.FlatAppearance.CheckedBackColor = global::System.Drawing.Color.Red;
			this.SR.FlatAppearance.MouseDownBackColor = global::System.Drawing.Color.FromArgb(192, 192, 0);
			this.SR.FlatAppearance.MouseOverBackColor = global::System.Drawing.Color.FromArgb(192, 0, 192);
			this.SR.Font = new global::System.Drawing.Font("Arial", 9.75f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.SR.ForeColor = global::System.Drawing.Color.White;
			global::System.Windows.Forms.Control sr = this.SR;
			location = new global::System.Drawing.Point(9, 72);
			sr.Location = location;
			this.SR.Name = "SR";
			global::System.Windows.Forms.Control sr2 = this.SR;
			size = new global::System.Drawing.Size(99, 23);
			sr2.Size = size;
			this.SR.TabIndex = 2;
			this.SR.TabStop = true;
			this.SR.Text = "Bhav (Rate)";
			this.SR.UseVisualStyleBackColor = false;
			this.SA.BackColor = global::System.Drawing.Color.FromArgb(192, 192, 0);
			this.SA.FlatAppearance.BorderSize = 2;
			this.SA.FlatAppearance.CheckedBackColor = global::System.Drawing.Color.Red;
			this.SA.FlatAppearance.MouseDownBackColor = global::System.Drawing.Color.FromArgb(192, 192, 0);
			this.SA.FlatAppearance.MouseOverBackColor = global::System.Drawing.Color.FromArgb(192, 0, 192);
			this.SA.Font = new global::System.Drawing.Font("Arial", 9.75f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.SA.ForeColor = global::System.Drawing.Color.White;
			global::System.Windows.Forms.Control sa = this.SA;
			location = new global::System.Drawing.Point(273, 40);
			sa.Location = location;
			this.SA.Name = "SA";
			global::System.Windows.Forms.Control sa2 = this.SA;
			size = new global::System.Drawing.Size(89, 23);
			sa2.Size = size;
			this.SA.TabIndex = 1;
			this.SA.TabStop = true;
			this.SA.Text = "Amount";
			this.SA.UseVisualStyleBackColor = false;
			this.SN.BackColor = global::System.Drawing.Color.FromArgb(192, 192, 0);
			this.SN.FlatAppearance.BorderSize = 2;
			this.SN.FlatAppearance.CheckedBackColor = global::System.Drawing.Color.Red;
			this.SN.FlatAppearance.MouseDownBackColor = global::System.Drawing.Color.FromArgb(192, 192, 0);
			this.SN.FlatAppearance.MouseOverBackColor = global::System.Drawing.Color.FromArgb(192, 0, 192);
			this.SN.Font = new global::System.Drawing.Font("Arial", 9.75f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.SN.ForeColor = global::System.Drawing.Color.White;
			global::System.Windows.Forms.Control sn = this.SN;
			location = new global::System.Drawing.Point(9, 43);
			sn.Location = location;
			this.SN.Name = "SN";
			global::System.Windows.Forms.Control sn2 = this.SN;
			size = new global::System.Drawing.Size(99, 23);
			sn2.Size = size;
			this.SN.TabIndex = 0;
			this.SN.TabStop = true;
			this.SN.Text = "Name";
			this.SN.UseVisualStyleBackColor = false;
			this.GroupBox2.Controls.Add(this.txtteam);
			this.GroupBox2.Controls.Add(this.txtrate);
			this.GroupBox2.Controls.Add(this.txtamount);
			this.GroupBox2.Controls.Add(this.txtname);
			this.GroupBox2.Controls.Add(this.Rteam);
			this.GroupBox2.Controls.Add(this.Rrate);
			this.GroupBox2.Controls.Add(this.Ramunt);
			this.GroupBox2.Controls.Add(this.RA);
			this.GroupBox2.FlatStyle = global::System.Windows.Forms.FlatStyle.Popup;
			this.GroupBox2.Font = new global::System.Drawing.Font("Verdana", 9.75f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.GroupBox2.ForeColor = global::System.Drawing.Color.FromArgb(192, 0, 192);
			global::System.Windows.Forms.Control groupBox3 = this.GroupBox2;
			location = new global::System.Drawing.Point(3, 18);
			groupBox3.Location = location;
			this.GroupBox2.Name = "GroupBox2";
			global::System.Windows.Forms.Control groupBox4 = this.GroupBox2;
			size = new global::System.Drawing.Size(480, 77);
			groupBox4.Size = size;
			this.GroupBox2.TabIndex = 3;
			this.GroupBox2.TabStop = false;
			this.GroupBox2.Text = "Fo Match";
			this.txtteam.BackColor = global::System.Drawing.Color.FromArgb(192, 255, 192);
			this.txtteam.CharacterCasing = global::System.Windows.Forms.CharacterCasing.Upper;
			this.txtteam.Font = new global::System.Drawing.Font("Arial", 9.75f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			global::System.Windows.Forms.Control txtteam = this.txtteam;
			location = new global::System.Drawing.Point(358, 48);
			txtteam.Location = location;
			this.txtteam.Name = "txtteam";
			global::System.Windows.Forms.Control txtteam2 = this.txtteam;
			size = new global::System.Drawing.Size(111, 22);
			txtteam2.Size = size;
			this.txtteam.TabIndex = 14;
			this.txtrate.BackColor = global::System.Drawing.Color.FromArgb(192, 255, 192);
			this.txtrate.CharacterCasing = global::System.Windows.Forms.CharacterCasing.Upper;
			this.txtrate.Font = new global::System.Drawing.Font("Arial", 9.75f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			global::System.Windows.Forms.Control txtrate = this.txtrate;
			location = new global::System.Drawing.Point(115, 47);
			txtrate.Location = location;
			this.txtrate.Name = "txtrate";
			global::System.Windows.Forms.Control txtrate2 = this.txtrate;
			size = new global::System.Drawing.Size(152, 22);
			txtrate2.Size = size;
			this.txtrate.TabIndex = 13;
			this.txtamount.BackColor = global::System.Drawing.Color.FromArgb(192, 255, 192);
			this.txtamount.CharacterCasing = global::System.Windows.Forms.CharacterCasing.Upper;
			this.txtamount.Font = new global::System.Drawing.Font("Arial", 9.75f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			global::System.Windows.Forms.Control txtamount = this.txtamount;
			location = new global::System.Drawing.Point(358, 18);
			txtamount.Location = location;
			this.txtamount.Name = "txtamount";
			global::System.Windows.Forms.Control txtamount2 = this.txtamount;
			size = new global::System.Drawing.Size(111, 22);
			txtamount2.Size = size;
			this.txtamount.TabIndex = 12;
			this.txtname.BackColor = global::System.Drawing.Color.FromArgb(192, 255, 192);
			this.txtname.DropDownStyle = global::System.Windows.Forms.ComboBoxStyle.Simple;
			this.txtname.Font = new global::System.Drawing.Font("Arial", 9.75f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.txtname.FormattingEnabled = true;
			global::System.Windows.Forms.Control txtname = this.txtname;
			location = new global::System.Drawing.Point(115, 17);
			txtname.Location = location;
			this.txtname.Name = "txtname";
			global::System.Windows.Forms.Control txtname2 = this.txtname;
			size = new global::System.Drawing.Size(152, 24);
			txtname2.Size = size;
			this.txtname.TabIndex = 11;
			this.Rteam.BackColor = global::System.Drawing.Color.FromArgb(192, 192, 0);
			this.Rteam.FlatAppearance.BorderSize = 2;
			this.Rteam.FlatAppearance.CheckedBackColor = global::System.Drawing.Color.Red;
			this.Rteam.FlatAppearance.MouseDownBackColor = global::System.Drawing.Color.FromArgb(192, 192, 0);
			this.Rteam.FlatAppearance.MouseOverBackColor = global::System.Drawing.Color.FromArgb(192, 0, 192);
			this.Rteam.Font = new global::System.Drawing.Font("Arial", 9.75f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Rteam.ForeColor = global::System.Drawing.Color.White;
			global::System.Windows.Forms.Control rteam = this.Rteam;
			location = new global::System.Drawing.Point(273, 47);
			rteam.Location = location;
			this.Rteam.Name = "Rteam";
			global::System.Windows.Forms.Control rteam2 = this.Rteam;
			size = new global::System.Drawing.Size(82, 23);
			rteam2.Size = size;
			this.Rteam.TabIndex = 3;
			this.Rteam.TabStop = true;
			this.Rteam.Text = "Team";
			this.Rteam.UseVisualStyleBackColor = false;
			this.Rrate.BackColor = global::System.Drawing.Color.FromArgb(192, 192, 0);
			this.Rrate.FlatAppearance.BorderSize = 2;
			this.Rrate.FlatAppearance.CheckedBackColor = global::System.Drawing.Color.Red;
			this.Rrate.FlatAppearance.MouseDownBackColor = global::System.Drawing.Color.FromArgb(192, 192, 0);
			this.Rrate.FlatAppearance.MouseOverBackColor = global::System.Drawing.Color.FromArgb(192, 0, 192);
			this.Rrate.Font = new global::System.Drawing.Font("Arial", 9.75f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Rrate.ForeColor = global::System.Drawing.Color.White;
			global::System.Windows.Forms.Control rrate = this.Rrate;
			location = new global::System.Drawing.Point(9, 47);
			rrate.Location = location;
			this.Rrate.Name = "Rrate";
			global::System.Windows.Forms.Control rrate2 = this.Rrate;
			size = new global::System.Drawing.Size(102, 23);
			rrate2.Size = size;
			this.Rrate.TabIndex = 2;
			this.Rrate.TabStop = true;
			this.Rrate.Text = "Bhav (Rate)";
			this.Rrate.UseVisualStyleBackColor = false;
			this.Ramunt.BackColor = global::System.Drawing.Color.FromArgb(192, 192, 0);
			this.Ramunt.FlatAppearance.BorderSize = 2;
			this.Ramunt.FlatAppearance.CheckedBackColor = global::System.Drawing.Color.Red;
			this.Ramunt.FlatAppearance.MouseDownBackColor = global::System.Drawing.Color.FromArgb(192, 192, 0);
			this.Ramunt.FlatAppearance.MouseOverBackColor = global::System.Drawing.Color.FromArgb(192, 0, 192);
			this.Ramunt.Font = new global::System.Drawing.Font("Arial", 9.75f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Ramunt.ForeColor = global::System.Drawing.Color.White;
			global::System.Windows.Forms.Control ramunt = this.Ramunt;
			location = new global::System.Drawing.Point(273, 18);
			ramunt.Location = location;
			this.Ramunt.Name = "Ramunt";
			global::System.Windows.Forms.Control ramunt2 = this.Ramunt;
			size = new global::System.Drawing.Size(82, 23);
			ramunt2.Size = size;
			this.Ramunt.TabIndex = 1;
			this.Ramunt.TabStop = true;
			this.Ramunt.Text = "Amount";
			this.Ramunt.UseVisualStyleBackColor = false;
			this.RA.BackColor = global::System.Drawing.Color.FromArgb(192, 192, 0);
			this.RA.FlatAppearance.BorderSize = 2;
			this.RA.FlatAppearance.CheckedBackColor = global::System.Drawing.Color.Red;
			this.RA.FlatAppearance.MouseDownBackColor = global::System.Drawing.Color.FromArgb(192, 192, 0);
			this.RA.FlatAppearance.MouseOverBackColor = global::System.Drawing.Color.FromArgb(192, 0, 192);
			this.RA.Font = new global::System.Drawing.Font("Arial", 9.75f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.RA.ForeColor = global::System.Drawing.Color.White;
			global::System.Windows.Forms.Control ra = this.RA;
			location = new global::System.Drawing.Point(9, 18);
			ra.Location = location;
			this.RA.Name = "RA";
			global::System.Windows.Forms.Control ra2 = this.RA;
			size = new global::System.Drawing.Size(102, 23);
			ra2.Size = size;
			this.RA.TabIndex = 0;
			this.RA.TabStop = true;
			this.RA.Text = "Name";
			this.RA.UseVisualStyleBackColor = false;
			this.Label2.BackColor = global::System.Drawing.Color.FromArgb(0, 192, 192);
			this.Label2.BorderStyle = global::System.Windows.Forms.BorderStyle.FixedSingle;
			this.Label2.Dock = global::System.Windows.Forms.DockStyle.Top;
			this.Label2.Font = new global::System.Drawing.Font("Verdana", 9f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label2.ForeColor = global::System.Drawing.Color.White;
			global::System.Windows.Forms.Control label3 = this.Label2;
			location = new global::System.Drawing.Point(0, 0);
			label3.Location = location;
			this.Label2.Name = "Label2";
			global::System.Windows.Forms.Control label4 = this.Label2;
			size = new global::System.Drawing.Size(654, 18);
			label4.Size = size;
			this.Label2.TabIndex = 1;
			this.Label2.Text = "SELECTION FOR MATCH / SESSTIONS";
			this.Label2.TextAlign = global::System.Drawing.ContentAlignment.MiddleCenter;
			this.Panel2.BorderStyle = global::System.Windows.Forms.BorderStyle.FixedSingle;
			this.Panel2.Controls.Add(this.SplitContainer2);
			this.Panel2.Dock = global::System.Windows.Forms.DockStyle.Fill;
			global::System.Windows.Forms.Control panel3 = this.Panel2;
			location = new global::System.Drawing.Point(0, 245);
			panel3.Location = location;
			this.Panel2.Name = "Panel2";
			global::System.Windows.Forms.Control panel4 = this.Panel2;
			size = new global::System.Drawing.Size(1354, 488);
			panel4.Size = size;
			this.Panel2.TabIndex = 1;
			this.SplitContainer2.Dock = global::System.Windows.Forms.DockStyle.Fill;
			global::System.Windows.Forms.Control splitContainer3 = this.SplitContainer2;
			location = new global::System.Drawing.Point(0, 0);
			splitContainer3.Location = location;
			this.SplitContainer2.Name = "SplitContainer2";
			this.SplitContainer2.Panel1.Controls.Add(this.DataGridView2);
			this.SplitContainer2.Panel1.Font = new global::System.Drawing.Font("Verdana", 9.75f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.SplitContainer2.Panel2.Controls.Add(this.DataGridView3);
			this.SplitContainer2.Panel2.Font = new global::System.Drawing.Font("Verdana", 9.75f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			global::System.Windows.Forms.Control splitContainer4 = this.SplitContainer2;
			size = new global::System.Drawing.Size(1352, 486);
			splitContainer4.Size = size;
			this.SplitContainer2.SplitterDistance = 690;
			this.SplitContainer2.TabIndex = 0;
			this.DataGridView2.AllowUserToAddRows = false;
			this.DataGridView2.AllowUserToDeleteRows = false;
			this.DataGridView2.AllowUserToOrderColumns = true;
			this.DataGridView2.AllowUserToResizeColumns = false;
			this.DataGridView2.AllowUserToResizeRows = false;
			this.DataGridView2.AutoSizeColumnsMode = global::System.Windows.Forms.DataGridViewAutoSizeColumnsMode.DisplayedCells;
			this.DataGridView2.BackgroundColor = global::System.Drawing.SystemColors.Control;
			dataGridViewCellStyle2.Alignment = global::System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
			dataGridViewCellStyle2.BackColor = global::System.Drawing.Color.LightSteelBlue;
			dataGridViewCellStyle2.Font = new global::System.Drawing.Font("Verdana", 9.75f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			dataGridViewCellStyle2.ForeColor = global::System.Drawing.Color.White;
			dataGridViewCellStyle2.SelectionBackColor = global::System.Drawing.Color.LightSteelBlue;
			dataGridViewCellStyle2.SelectionForeColor = global::System.Drawing.Color.White;
			dataGridViewCellStyle2.WrapMode = global::System.Windows.Forms.DataGridViewTriState.True;
			this.DataGridView2.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle2;
			dataGridViewCellStyle3.Alignment = global::System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
			dataGridViewCellStyle3.BackColor = global::System.Drawing.SystemColors.Window;
			dataGridViewCellStyle3.Font = new global::System.Drawing.Font("Verdana", 9.75f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			dataGridViewCellStyle3.ForeColor = global::System.Drawing.SystemColors.ControlText;
			dataGridViewCellStyle3.SelectionBackColor = global::System.Drawing.Color.DeepSkyBlue;
			dataGridViewCellStyle3.SelectionForeColor = global::System.Drawing.SystemColors.HighlightText;
			dataGridViewCellStyle3.WrapMode = global::System.Windows.Forms.DataGridViewTriState.False;
			this.DataGridView2.DefaultCellStyle = dataGridViewCellStyle3;
			this.DataGridView2.Dock = global::System.Windows.Forms.DockStyle.Fill;
			this.DataGridView2.EnableHeadersVisualStyles = false;
			this.DataGridView2.GridColor = global::System.Drawing.SystemColors.Control;
			global::System.Windows.Forms.Control dataGridView3 = this.DataGridView2;
			location = new global::System.Drawing.Point(0, 0);
			dataGridView3.Location = location;
			this.DataGridView2.Name = "DataGridView2";
			this.DataGridView2.ReadOnly = true;
			this.DataGridView2.RowHeadersVisible = false;
			global::System.Windows.Forms.Control dataGridView4 = this.DataGridView2;
			size = new global::System.Drawing.Size(690, 486);
			dataGridView4.Size = size;
			this.DataGridView2.TabIndex = 1;
			this.DataGridView3.AllowUserToAddRows = false;
			this.DataGridView3.AllowUserToDeleteRows = false;
			this.DataGridView3.AllowUserToOrderColumns = true;
			this.DataGridView3.AllowUserToResizeColumns = false;
			this.DataGridView3.AllowUserToResizeRows = false;
			this.DataGridView3.AutoSizeColumnsMode = global::System.Windows.Forms.DataGridViewAutoSizeColumnsMode.DisplayedCells;
			this.DataGridView3.BackgroundColor = global::System.Drawing.SystemColors.Control;
			this.DataGridView3.ColumnHeadersBorderStyle = global::System.Windows.Forms.DataGridViewHeaderBorderStyle.Single;
			dataGridViewCellStyle4.Alignment = global::System.Windows.Forms.DataGridViewContentAlignment.MiddleCenter;
			dataGridViewCellStyle4.BackColor = global::System.Drawing.Color.LightBlue;
			dataGridViewCellStyle4.Font = new global::System.Drawing.Font("Verdana", 9.75f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			dataGridViewCellStyle4.ForeColor = global::System.Drawing.Color.Black;
			dataGridViewCellStyle4.WrapMode = global::System.Windows.Forms.DataGridViewTriState.True;
			this.DataGridView3.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle4;
			this.DataGridView3.ColumnHeadersHeight = 25;
			this.DataGridView3.ColumnHeadersHeightSizeMode = global::System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.DisableResizing;
			dataGridViewCellStyle5.Alignment = global::System.Windows.Forms.DataGridViewContentAlignment.MiddleRight;
			dataGridViewCellStyle5.BackColor = global::System.Drawing.SystemColors.Window;
			dataGridViewCellStyle5.Font = new global::System.Drawing.Font("Verdana", 9.75f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			dataGridViewCellStyle5.ForeColor = global::System.Drawing.SystemColors.ControlText;
			dataGridViewCellStyle5.SelectionBackColor = global::System.Drawing.SystemColors.Highlight;
			dataGridViewCellStyle5.SelectionForeColor = global::System.Drawing.SystemColors.HighlightText;
			dataGridViewCellStyle5.WrapMode = global::System.Windows.Forms.DataGridViewTriState.True;
			this.DataGridView3.DefaultCellStyle = dataGridViewCellStyle5;
			this.DataGridView3.Dock = global::System.Windows.Forms.DockStyle.Fill;
			this.DataGridView3.EnableHeadersVisualStyles = false;
			this.DataGridView3.GridColor = global::System.Drawing.Color.FromArgb(224, 224, 224);
			global::System.Windows.Forms.Control dataGridView5 = this.DataGridView3;
			location = new global::System.Drawing.Point(0, 0);
			dataGridView5.Location = location;
			this.DataGridView3.MultiSelect = false;
			this.DataGridView3.Name = "DataGridView3";
			this.DataGridView3.ReadOnly = true;
			this.DataGridView3.RowHeadersVisible = false;
			this.DataGridView3.RowHeadersWidthSizeMode = global::System.Windows.Forms.DataGridViewRowHeadersWidthSizeMode.DisableResizing;
			this.DataGridView3.RowTemplate.ReadOnly = true;
			this.DataGridView3.SelectionMode = global::System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
			global::System.Windows.Forms.Control dataGridView6 = this.DataGridView3;
			size = new global::System.Drawing.Size(658, 486);
			dataGridView6.Size = size;
			this.DataGridView3.TabIndex = 22;
			global::System.Drawing.SizeF autoScaleDimensions = new global::System.Drawing.SizeF(8f, 16f);
			this.AutoScaleDimensions = autoScaleDimensions;
			this.AutoScaleMode = global::System.Windows.Forms.AutoScaleMode.Font;
			size = new global::System.Drawing.Size(1354, 733);
			this.ClientSize = size;
			this.Controls.Add(this.Panel2);
			this.Controls.Add(this.Panel1);
			this.Font = new global::System.Drawing.Font("Verdana", 9.75f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			global::System.Windows.Forms.Padding margin = new global::System.Windows.Forms.Padding(4);
			this.Margin = margin;
			this.Name = "Frm_FinalSudaEntry";
			this.Panel1.ResumeLayout(false);
			this.SplitContainer1.Panel1.ResumeLayout(false);
			this.SplitContainer1.Panel2.ResumeLayout(false);
			this.SplitContainer1.Panel2.PerformLayout();
			this.SplitContainer1.ResumeLayout(false);
			((global::System.ComponentModel.ISupportInitialize)this.DataGridView1).EndInit();
			this.GroupBox3.ResumeLayout(false);
			this.GroupBox3.PerformLayout();
			this.GroupBox2.ResumeLayout(false);
			this.GroupBox2.PerformLayout();
			this.Panel2.ResumeLayout(false);
			this.SplitContainer2.Panel1.ResumeLayout(false);
			this.SplitContainer2.Panel2.ResumeLayout(false);
			this.SplitContainer2.ResumeLayout(false);
			((global::System.ComponentModel.ISupportInitialize)this.DataGridView2).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.DataGridView3).EndInit();
			this.ResumeLayout(false);
		}

		// Token: 0x04000505 RID: 1285
		private global::System.ComponentModel.IContainer components;
	}
}
