namespace YashAksh
{
	// Token: 0x020000C7 RID: 199
	[global::Microsoft.VisualBasic.CompilerServices.DesignerGenerated]
	public partial class SessionDelear : global::System.Windows.Forms.Form
	{
		// Token: 0x06002142 RID: 8514 RVA: 0x003AA84C File Offset: 0x003A8C4C
		[global::System.Diagnostics.DebuggerNonUserCode]
		protected override void Dispose(bool disposing)
		{
			try
			{
				if (disposing && this.components != null)
				{
					this.components.Dispose();
				}
			}
			finally
			{
				base.Dispose(disposing);
			}
		}

		// Token: 0x06002143 RID: 8515 RVA: 0x003AA88C File Offset: 0x003A8C8C
		[global::System.Diagnostics.DebuggerStepThrough]
		private void InitializeComponent()
		{
			this.components = new global::System.ComponentModel.Container();
			global::System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle = new global::System.Windows.Forms.DataGridViewCellStyle();
			global::System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle2 = new global::System.Windows.Forms.DataGridViewCellStyle();
			global::System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle3 = new global::System.Windows.Forms.DataGridViewCellStyle();
			global::System.ComponentModel.ComponentResourceManager componentResourceManager = new global::System.ComponentModel.ComponentResourceManager(typeof(global::YashAksh.SessionDelear));
			this.Button2 = new global::System.Windows.Forms.Button();
			this.Save = new global::System.Windows.Forms.Button();
			this.GroupBox3 = new global::System.Windows.Forms.GroupBox();
			this.CheckBox1 = new global::System.Windows.Forms.CheckBox();
			this.Label3 = new global::System.Windows.Forms.Label();
			this.txtrun = new global::System.Windows.Forms.TextBox();
			this.Label4 = new global::System.Windows.Forms.Label();
			this.txtdeclard = new global::System.Windows.Forms.TextBox();
			this.Label2 = new global::System.Windows.Forms.Label();
			this.Label1 = new global::System.Windows.Forms.Label();
			this.txtdecl = new global::System.Windows.Forms.TextBox();
			this.Button1 = new global::System.Windows.Forms.Button();
			this.txtpname = new global::System.Windows.Forms.ComboBox();
			this.datagridmen = new global::System.Windows.Forms.DataGridView();
			this.Column4 = new global::System.Windows.Forms.DataGridViewTextBoxColumn();
			this.Column5 = new global::System.Windows.Forms.DataGridViewTextBoxColumn();
			this.Button3 = new global::System.Windows.Forms.Button();
			this.TextBox2 = new global::System.Windows.Forms.TextBox();
			this.Button4 = new global::System.Windows.Forms.Button();
			this.DataGridView1 = new global::System.Windows.Forms.DataGridView();
			this.Column1 = new global::System.Windows.Forms.DataGridViewTextBoxColumn();
			this.Column2 = new global::System.Windows.Forms.DataGridViewTextBoxColumn();
			this.Column3 = new global::System.Windows.Forms.DataGridViewTextBoxColumn();
			this.TextBox3 = new global::System.Windows.Forms.ComboBox();
			this.TextBox1 = new global::System.Windows.Forms.TextBox();
			this.txtagentparsent = new global::System.Windows.Forms.ComboBox();
			this.txtself = new global::System.Windows.Forms.ComboBox();
			this.Timer1 = new global::System.Windows.Forms.Timer(this.components);
			this.Button5 = new global::System.Windows.Forms.Button();
			this.txtpartyname = new global::System.Windows.Forms.ComboBox();
			this.txtagentname = new global::System.Windows.Forms.ComboBox();
			this.txtpatnarname = new global::System.Windows.Forms.ComboBox();
			this.txtpatnarparsent = new global::System.Windows.Forms.ComboBox();
			this.txtcomission = new global::System.Windows.Forms.ComboBox();
			this.txttype = new global::System.Windows.Forms.Label();
			this.Timer2 = new global::System.Windows.Forms.Timer(this.components);
			this.Button6 = new global::System.Windows.Forms.Button();
			this.DataSelf = new global::System.Windows.Forms.DataGridView();
			this.DataGridViewTextBoxColumn1 = new global::System.Windows.Forms.DataGridViewTextBoxColumn();
			this.DataGridViewTextBoxColumn2 = new global::System.Windows.Forms.DataGridViewTextBoxColumn();
			this.DataGridViewTextBoxColumn3 = new global::System.Windows.Forms.DataGridViewTextBoxColumn();
			this.Dataagent = new global::System.Windows.Forms.DataGridView();
			this.DataGridViewTextBoxColumn4 = new global::System.Windows.Forms.DataGridViewTextBoxColumn();
			this.DataGridViewTextBoxColumn5 = new global::System.Windows.Forms.DataGridViewTextBoxColumn();
			this.DataGridViewTextBoxColumn6 = new global::System.Windows.Forms.DataGridViewTextBoxColumn();
			this.Datapatner = new global::System.Windows.Forms.DataGridView();
			this.DataGridViewTextBoxColumn7 = new global::System.Windows.Forms.DataGridViewTextBoxColumn();
			this.DataGridViewTextBoxColumn8 = new global::System.Windows.Forms.DataGridViewTextBoxColumn();
			this.DataGridViewTextBoxColumn9 = new global::System.Windows.Forms.DataGridViewTextBoxColumn();
			this.Datacomision = new global::System.Windows.Forms.DataGridView();
			this.DataGridViewTextBoxColumn10 = new global::System.Windows.Forms.DataGridViewTextBoxColumn();
			this.DataGridViewTextBoxColumn11 = new global::System.Windows.Forms.DataGridViewTextBoxColumn();
			this.DataGridViewTextBoxColumn12 = new global::System.Windows.Forms.DataGridViewTextBoxColumn();
			this.DataGridView2 = new global::System.Windows.Forms.DataGridView();
			this.DataGridViewTextBoxColumn13 = new global::System.Windows.Forms.DataGridViewTextBoxColumn();
			this.DataGridViewTextBoxColumn14 = new global::System.Windows.Forms.DataGridViewTextBoxColumn();
			this.DataGridViewTextBoxColumn15 = new global::System.Windows.Forms.DataGridViewTextBoxColumn();
			this.Button7 = new global::System.Windows.Forms.Button();
			this.Button8 = new global::System.Windows.Forms.Button();
			this.Button9 = new global::System.Windows.Forms.Button();
			this.Button10 = new global::System.Windows.Forms.Button();
			this.Button11 = new global::System.Windows.Forms.Button();
			this.Button12 = new global::System.Windows.Forms.Button();
			this.AgentTransfar = new global::System.Windows.Forms.ComboBox();
			this.PatnareTransfar = new global::System.Windows.Forms.ComboBox();
			this.Label5 = new global::System.Windows.Forms.Label();
			this.txtdate = new global::System.Windows.Forms.DateTimePicker();
			this.Panel1 = new global::System.Windows.Forms.Panel();
			this.Panel2 = new global::System.Windows.Forms.Panel();
			this.Panel3 = new global::System.Windows.Forms.Panel();
			this.GroupBox3.SuspendLayout();
			((global::System.ComponentModel.ISupportInitialize)this.datagridmen).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.DataGridView1).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.DataSelf).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.Dataagent).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.Datapatner).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.Datacomision).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.DataGridView2).BeginInit();
			this.SuspendLayout();
			this.Button2.DialogResult = global::System.Windows.Forms.DialogResult.Cancel;
			this.Button2.Font = new global::System.Drawing.Font("Arial", 12f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			global::System.Windows.Forms.Control button = this.Button2;
			global::System.Drawing.Point location = new global::System.Drawing.Point(736, 207);
			button.Location = location;
			global::System.Windows.Forms.Control button2 = this.Button2;
			global::System.Windows.Forms.Padding padding = new global::System.Windows.Forms.Padding(4);
			button2.Margin = padding;
			this.Button2.Name = "Button2";
			global::System.Windows.Forms.Control button3 = this.Button2;
			global::System.Drawing.Size size = new global::System.Drawing.Size(65, 30);
			button3.Size = size;
			this.Button2.TabIndex = 1;
			this.Button2.Text = "&Close";
			this.Button2.UseVisualStyleBackColor = true;
			this.Save.Font = new global::System.Drawing.Font("Arial", 12f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			global::System.Windows.Forms.Control save = this.Save;
			location = new global::System.Drawing.Point(422, 208);
			save.Location = location;
			global::System.Windows.Forms.Control save2 = this.Save;
			padding = new global::System.Windows.Forms.Padding(4);
			save2.Margin = padding;
			this.Save.Name = "Save";
			global::System.Windows.Forms.Control save3 = this.Save;
			size = new global::System.Drawing.Size(72, 30);
			save3.Size = size;
			this.Save.TabIndex = 0;
			this.Save.Text = "&Save";
			this.Save.UseVisualStyleBackColor = true;
			this.GroupBox3.Controls.Add(this.CheckBox1);
			this.GroupBox3.Controls.Add(this.Label3);
			this.GroupBox3.Controls.Add(this.txtrun);
			this.GroupBox3.Font = new global::System.Drawing.Font("Arial", 12f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			global::System.Windows.Forms.Control groupBox = this.GroupBox3;
			location = new global::System.Drawing.Point(422, 84);
			groupBox.Location = location;
			global::System.Windows.Forms.Control groupBox2 = this.GroupBox3;
			padding = new global::System.Windows.Forms.Padding(4);
			groupBox2.Margin = padding;
			this.GroupBox3.Name = "GroupBox3";
			global::System.Windows.Forms.Control groupBox3 = this.GroupBox3;
			padding = new global::System.Windows.Forms.Padding(4);
			groupBox3.Padding = padding;
			global::System.Windows.Forms.Control groupBox4 = this.GroupBox3;
			size = new global::System.Drawing.Size(379, 119);
			groupBox4.Size = size;
			this.GroupBox3.TabIndex = 8;
			this.GroupBox3.TabStop = false;
			this.CheckBox1.AutoSize = true;
			this.CheckBox1.Enabled = false;
			global::System.Windows.Forms.Control checkBox = this.CheckBox1;
			location = new global::System.Drawing.Point(112, 75);
			checkBox.Location = location;
			this.CheckBox1.Name = "CheckBox1";
			global::System.Windows.Forms.Control checkBox2 = this.CheckBox1;
			size = new global::System.Drawing.Size(148, 23);
			checkBox2.Size = size;
			this.CheckBox1.TabIndex = 10;
			this.CheckBox1.Text = "BMB (ABN+TIE)";
			this.CheckBox1.UseVisualStyleBackColor = true;
			this.Label3.BackColor = global::System.Drawing.Color.SteelBlue;
			this.Label3.BorderStyle = global::System.Windows.Forms.BorderStyle.FixedSingle;
			this.Label3.ForeColor = global::System.Drawing.Color.White;
			global::System.Windows.Forms.Control label = this.Label3;
			location = new global::System.Drawing.Point(112, 27);
			label.Location = location;
			this.Label3.Name = "Label3";
			global::System.Windows.Forms.Control label2 = this.Label3;
			size = new global::System.Drawing.Size(74, 25);
			label2.Size = size;
			this.Label3.TabIndex = 8;
			this.Label3.Text = "Runs";
			this.Label3.TextAlign = global::System.Drawing.ContentAlignment.MiddleCenter;
			this.txtrun.CharacterCasing = global::System.Windows.Forms.CharacterCasing.Upper;
			global::System.Windows.Forms.Control txtrun = this.txtrun;
			location = new global::System.Drawing.Point(188, 27);
			txtrun.Location = location;
			global::System.Windows.Forms.Control txtrun2 = this.txtrun;
			padding = new global::System.Windows.Forms.Padding(4);
			txtrun2.Margin = padding;
			this.txtrun.Name = "txtrun";
			global::System.Windows.Forms.Control txtrun3 = this.txtrun;
			size = new global::System.Drawing.Size(65, 26);
			txtrun3.Size = size;
			this.txtrun.TabIndex = 7;
			this.txtrun.TextAlign = global::System.Windows.Forms.HorizontalAlignment.Center;
			this.Label4.BackColor = global::System.Drawing.Color.SteelBlue;
			this.Label4.BorderStyle = global::System.Windows.Forms.BorderStyle.FixedSingle;
			this.Label4.ForeColor = global::System.Drawing.Color.White;
			global::System.Windows.Forms.Control label3 = this.Label4;
			location = new global::System.Drawing.Point(751, 415);
			label3.Location = location;
			this.Label4.Name = "Label4";
			global::System.Windows.Forms.Control label4 = this.Label4;
			size = new global::System.Drawing.Size(142, 25);
			label4.Size = size;
			this.Label4.TabIndex = 9;
			this.Label4.Text = "Declared By";
			this.Label4.TextAlign = global::System.Drawing.ContentAlignment.MiddleCenter;
			this.Label4.UseWaitCursor = true;
			this.txtdeclard.CharacterCasing = global::System.Windows.Forms.CharacterCasing.Upper;
			global::System.Windows.Forms.Control txtdeclard = this.txtdeclard;
			location = new global::System.Drawing.Point(900, 417);
			txtdeclard.Location = location;
			global::System.Windows.Forms.Control txtdeclard2 = this.txtdeclard;
			padding = new global::System.Windows.Forms.Padding(4);
			txtdeclard2.Margin = padding;
			this.txtdeclard.Name = "txtdeclard";
			global::System.Windows.Forms.Control txtdeclard3 = this.txtdeclard;
			size = new global::System.Drawing.Size(213, 22);
			txtdeclard3.Size = size;
			this.txtdeclard.TabIndex = 6;
			this.txtdeclard.TextAlign = global::System.Windows.Forms.HorizontalAlignment.Center;
			this.txtdeclard.UseWaitCursor = true;
			this.Label2.BackColor = global::System.Drawing.Color.SteelBlue;
			this.Label2.BorderStyle = global::System.Windows.Forms.BorderStyle.FixedSingle;
			this.Label2.Font = new global::System.Drawing.Font("Arial", 12f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label2.ForeColor = global::System.Drawing.Color.White;
			global::System.Windows.Forms.Control label5 = this.Label2;
			location = new global::System.Drawing.Point(422, 48);
			label5.Location = location;
			global::System.Windows.Forms.Control label6 = this.Label2;
			padding = new global::System.Windows.Forms.Padding(4, 0, 4, 0);
			label6.Margin = padding;
			this.Label2.Name = "Label2";
			global::System.Windows.Forms.Control label7 = this.Label2;
			size = new global::System.Drawing.Size(379, 32);
			label7.Size = size;
			this.Label2.TabIndex = 0;
			this.Label2.TextAlign = global::System.Drawing.ContentAlignment.MiddleCenter;
			this.Label1.BackColor = global::System.Drawing.Color.SteelBlue;
			this.Label1.BorderStyle = global::System.Windows.Forms.BorderStyle.FixedSingle;
			this.Label1.Dock = global::System.Windows.Forms.DockStyle.Top;
			this.Label1.Font = new global::System.Drawing.Font("Arial", 12f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label1.ForeColor = global::System.Drawing.Color.White;
			global::System.Windows.Forms.Control label8 = this.Label1;
			location = new global::System.Drawing.Point(0, 0);
			label8.Location = location;
			global::System.Windows.Forms.Control label9 = this.Label1;
			padding = new global::System.Windows.Forms.Padding(4, 0, 4, 0);
			label9.Margin = padding;
			this.Label1.Name = "Label1";
			global::System.Windows.Forms.Control label10 = this.Label1;
			size = new global::System.Drawing.Size(1276, 30);
			label10.Size = size;
			this.Label1.TabIndex = 5;
			this.Label1.Text = "Declare Match";
			this.Label1.TextAlign = global::System.Drawing.ContentAlignment.MiddleCenter;
			global::System.Windows.Forms.Control txtdecl = this.txtdecl;
			location = new global::System.Drawing.Point(1058, 77);
			txtdecl.Location = location;
			global::System.Windows.Forms.Control txtdecl2 = this.txtdecl;
			padding = new global::System.Windows.Forms.Padding(4);
			txtdecl2.Margin = padding;
			this.txtdecl.Name = "txtdecl";
			global::System.Windows.Forms.Control txtdecl3 = this.txtdecl;
			size = new global::System.Drawing.Size(75, 22);
			txtdecl3.Size = size;
			this.txtdecl.TabIndex = 10;
			this.txtdecl.Text = "Declared";
			global::System.Windows.Forms.Control button4 = this.Button1;
			location = new global::System.Drawing.Point(871, 102);
			button4.Location = location;
			this.Button1.Name = "Button1";
			global::System.Windows.Forms.Control button5 = this.Button1;
			size = new global::System.Drawing.Size(85, 25);
			button5.Size = size;
			this.Button1.TabIndex = 11;
			this.Button1.Text = "Run ";
			this.Button1.UseVisualStyleBackColor = true;
			this.txtpname.FormattingEnabled = true;
			global::System.Windows.Forms.Control txtpname = this.txtpname;
			location = new global::System.Drawing.Point(871, 48);
			txtpname.Location = location;
			this.txtpname.Name = "txtpname";
			global::System.Windows.Forms.Control txtpname2 = this.txtpname;
			size = new global::System.Drawing.Size(85, 24);
			txtpname2.Size = size;
			this.txtpname.TabIndex = 12;
			this.datagridmen.AllowUserToAddRows = false;
			this.datagridmen.AllowUserToDeleteRows = false;
			this.datagridmen.BackgroundColor = global::System.Drawing.SystemColors.Control;
			this.datagridmen.BorderStyle = global::System.Windows.Forms.BorderStyle.Fixed3D;
			dataGridViewCellStyle.Alignment = global::System.Windows.Forms.DataGridViewContentAlignment.MiddleRight;
			dataGridViewCellStyle.BackColor = global::System.Drawing.Color.LightSlateGray;
			dataGridViewCellStyle.Font = new global::System.Drawing.Font("Arial", 9.75f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			dataGridViewCellStyle.ForeColor = global::System.Drawing.Color.White;
			dataGridViewCellStyle.SelectionBackColor = global::System.Drawing.Color.LightSlateGray;
			dataGridViewCellStyle.SelectionForeColor = global::System.Drawing.Color.White;
			this.datagridmen.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle;
			this.datagridmen.ColumnHeadersHeightSizeMode = global::System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.DisableResizing;
			this.datagridmen.Columns.AddRange(new global::System.Windows.Forms.DataGridViewColumn[]
			{
				this.Column4,
				this.Column5
			});
			this.datagridmen.Cursor = global::System.Windows.Forms.Cursors.Hand;
			dataGridViewCellStyle2.Alignment = global::System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
			dataGridViewCellStyle2.BackColor = global::System.Drawing.SystemColors.Window;
			dataGridViewCellStyle2.Font = new global::System.Drawing.Font("Arial", 9.75f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			dataGridViewCellStyle2.ForeColor = global::System.Drawing.Color.Blue;
			dataGridViewCellStyle2.SelectionBackColor = global::System.Drawing.Color.WhiteSmoke;
			dataGridViewCellStyle2.SelectionForeColor = global::System.Drawing.Color.Blue;
			dataGridViewCellStyle2.WrapMode = global::System.Windows.Forms.DataGridViewTriState.False;
			this.datagridmen.DefaultCellStyle = dataGridViewCellStyle2;
			this.datagridmen.GridColor = global::System.Drawing.Color.Black;
			global::System.Windows.Forms.Control datagridmen = this.datagridmen;
			location = new global::System.Drawing.Point(871, 163);
			datagridmen.Location = location;
			this.datagridmen.Name = "datagridmen";
			this.datagridmen.ReadOnly = true;
			dataGridViewCellStyle3.Alignment = global::System.Windows.Forms.DataGridViewContentAlignment.MiddleCenter;
			dataGridViewCellStyle3.BackColor = global::System.Drawing.SystemColors.Control;
			dataGridViewCellStyle3.Font = new global::System.Drawing.Font("Arial", 9.75f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			dataGridViewCellStyle3.ForeColor = global::System.Drawing.SystemColors.WindowText;
			dataGridViewCellStyle3.SelectionBackColor = global::System.Drawing.Color.White;
			dataGridViewCellStyle3.SelectionForeColor = global::System.Drawing.Color.Black;
			this.datagridmen.RowHeadersDefaultCellStyle = dataGridViewCellStyle3;
			this.datagridmen.RowHeadersVisible = false;
			this.datagridmen.RowHeadersWidthSizeMode = global::System.Windows.Forms.DataGridViewRowHeadersWidthSizeMode.DisableResizing;
			global::System.Windows.Forms.Control datagridmen2 = this.datagridmen;
			size = new global::System.Drawing.Size(307, 82);
			datagridmen2.Size = size;
			this.datagridmen.TabIndex = 5;
			this.Column4.HeaderText = "";
			this.Column4.Name = "Column4";
			this.Column4.ReadOnly = true;
			this.Column4.Width = 150;
			this.Column5.HeaderText = "";
			this.Column5.Name = "Column5";
			this.Column5.ReadOnly = true;
			this.Column5.Width = 150;
			global::System.Windows.Forms.Control button6 = this.Button3;
			location = new global::System.Drawing.Point(1058, 49);
			button6.Location = location;
			this.Button3.Name = "Button3";
			global::System.Windows.Forms.Control button7 = this.Button3;
			size = new global::System.Drawing.Size(75, 23);
			button7.Size = size;
			this.Button3.TabIndex = 69;
			this.Button3.Text = "Grid OK";
			this.Button3.UseVisualStyleBackColor = true;
			global::System.Windows.Forms.Control textBox = this.TextBox2;
			location = new global::System.Drawing.Point(871, 77);
			textBox.Location = location;
			global::System.Windows.Forms.Control textBox2 = this.TextBox2;
			padding = new global::System.Windows.Forms.Padding(4);
			textBox2.Margin = padding;
			this.TextBox2.Name = "TextBox2";
			global::System.Windows.Forms.Control textBox3 = this.TextBox2;
			size = new global::System.Drawing.Size(85, 22);
			textBox3.Size = size;
			this.TextBox2.TabIndex = 70;
			this.TextBox2.Text = "7";
			this.TextBox2.TextAlign = global::System.Windows.Forms.HorizontalAlignment.Center;
			global::System.Windows.Forms.Control button8 = this.Button4;
			location = new global::System.Drawing.Point(1139, 49);
			button8.Location = location;
			this.Button4.Name = "Button4";
			global::System.Windows.Forms.Control button9 = this.Button4;
			size = new global::System.Drawing.Size(75, 23);
			button9.Size = size;
			this.Button4.TabIndex = 71;
			this.Button4.Text = "Test";
			this.Button4.UseVisualStyleBackColor = true;
			this.DataGridView1.BackgroundColor = global::System.Drawing.SystemColors.Control;
			this.DataGridView1.Columns.AddRange(new global::System.Windows.Forms.DataGridViewColumn[]
			{
				this.Column1,
				this.Column2,
				this.Column3
			});
			this.DataGridView1.GridColor = global::System.Drawing.Color.FromArgb(128, 128, 255);
			global::System.Windows.Forms.Control dataGridView = this.DataGridView1;
			location = new global::System.Drawing.Point(22, 446);
			dataGridView.Location = location;
			this.DataGridView1.Name = "DataGridView1";
			this.DataGridView1.RowHeadersVisible = false;
			global::System.Windows.Forms.Control dataGridView2 = this.DataGridView1;
			size = new global::System.Drawing.Size(235, 100);
			dataGridView2.Size = size;
			this.DataGridView1.TabIndex = 73;
			this.Column1.HeaderText = "Party Name";
			this.Column1.Name = "Column1";
			this.Column1.ReadOnly = true;
			this.Column2.HeaderText = "Amount";
			this.Column2.Name = "Column2";
			this.Column2.ReadOnly = true;
			this.Column2.Width = 50;
			this.Column3.HeaderText = "Remark";
			this.Column3.Name = "Column3";
			this.Column3.ReadOnly = true;
			this.Column3.Width = 300;
			this.TextBox3.FormattingEnabled = true;
			global::System.Windows.Forms.Control textBox4 = this.TextBox3;
			location = new global::System.Drawing.Point(962, 48);
			textBox4.Location = location;
			this.TextBox3.Name = "TextBox3";
			global::System.Windows.Forms.Control textBox5 = this.TextBox3;
			size = new global::System.Drawing.Size(90, 24);
			textBox5.Size = size;
			this.TextBox3.TabIndex = 75;
			global::System.Windows.Forms.Control textBox6 = this.TextBox1;
			location = new global::System.Drawing.Point(910, 134);
			textBox6.Location = location;
			global::System.Windows.Forms.Control textBox7 = this.TextBox1;
			padding = new global::System.Windows.Forms.Padding(4);
			textBox7.Margin = padding;
			this.TextBox1.Name = "TextBox1";
			global::System.Windows.Forms.Control textBox8 = this.TextBox1;
			size = new global::System.Drawing.Size(46, 22);
			textBox8.Size = size;
			this.TextBox1.TabIndex = 74;
			this.TextBox1.TextAlign = global::System.Windows.Forms.HorizontalAlignment.Center;
			this.txtagentparsent.FormattingEnabled = true;
			global::System.Windows.Forms.Control txtagentparsent = this.txtagentparsent;
			location = new global::System.Drawing.Point(139, 221);
			txtagentparsent.Location = location;
			this.txtagentparsent.Name = "txtagentparsent";
			global::System.Windows.Forms.Control txtagentparsent2 = this.txtagentparsent;
			size = new global::System.Drawing.Size(67, 24);
			txtagentparsent2.Size = size;
			this.txtagentparsent.TabIndex = 76;
			this.txtself.FormattingEnabled = true;
			global::System.Windows.Forms.Control txtself = this.txtself;
			location = new global::System.Drawing.Point(139, 191);
			txtself.Location = location;
			this.txtself.Name = "txtself";
			global::System.Windows.Forms.Control txtself2 = this.txtself;
			size = new global::System.Drawing.Size(67, 24);
			txtself2.Size = size;
			this.txtself.TabIndex = 77;
			this.Timer1.Interval = 1;
			global::System.Windows.Forms.Control button10 = this.Button5;
			location = new global::System.Drawing.Point(12, 162);
			button10.Location = location;
			this.Button5.Name = "Button5";
			global::System.Windows.Forms.Control button11 = this.Button5;
			size = new global::System.Drawing.Size(75, 23);
			button11.Size = size;
			this.Button5.TabIndex = 78;
			this.Button5.Text = "Button5";
			this.Button5.UseVisualStyleBackColor = true;
			this.txtpartyname.FormattingEnabled = true;
			global::System.Windows.Forms.Control txtpartyname = this.txtpartyname;
			location = new global::System.Drawing.Point(12, 191);
			txtpartyname.Location = location;
			this.txtpartyname.Name = "txtpartyname";
			global::System.Windows.Forms.Control txtpartyname2 = this.txtpartyname;
			size = new global::System.Drawing.Size(121, 24);
			txtpartyname2.Size = size;
			this.txtpartyname.TabIndex = 79;
			this.txtagentname.FormattingEnabled = true;
			global::System.Windows.Forms.Control txtagentname = this.txtagentname;
			location = new global::System.Drawing.Point(12, 221);
			txtagentname.Location = location;
			this.txtagentname.Name = "txtagentname";
			global::System.Windows.Forms.Control txtagentname2 = this.txtagentname;
			size = new global::System.Drawing.Size(121, 24);
			txtagentname2.Size = size;
			this.txtagentname.TabIndex = 80;
			this.txtpatnarname.FormattingEnabled = true;
			global::System.Windows.Forms.Control txtpatnarname = this.txtpatnarname;
			location = new global::System.Drawing.Point(12, 251);
			txtpatnarname.Location = location;
			this.txtpatnarname.Name = "txtpatnarname";
			global::System.Windows.Forms.Control txtpatnarname2 = this.txtpatnarname;
			size = new global::System.Drawing.Size(121, 24);
			txtpatnarname2.Size = size;
			this.txtpatnarname.TabIndex = 83;
			this.txtpatnarparsent.FormattingEnabled = true;
			global::System.Windows.Forms.Control txtpatnarparsent = this.txtpatnarparsent;
			location = new global::System.Drawing.Point(139, 251);
			txtpatnarparsent.Location = location;
			this.txtpatnarparsent.Name = "txtpatnarparsent";
			global::System.Windows.Forms.Control txtpatnarparsent2 = this.txtpatnarparsent;
			size = new global::System.Drawing.Size(67, 24);
			txtpatnarparsent2.Size = size;
			this.txtpatnarparsent.TabIndex = 82;
			this.txtcomission.FormattingEnabled = true;
			global::System.Windows.Forms.Control txtcomission = this.txtcomission;
			location = new global::System.Drawing.Point(12, 281);
			txtcomission.Location = location;
			this.txtcomission.Name = "txtcomission";
			global::System.Windows.Forms.Control txtcomission2 = this.txtcomission;
			size = new global::System.Drawing.Size(121, 24);
			txtcomission2.Size = size;
			this.txtcomission.TabIndex = 84;
			this.txttype.AutoSize = true;
			global::System.Windows.Forms.Control txttype = this.txttype;
			location = new global::System.Drawing.Point(139, 284);
			txttype.Location = location;
			this.txttype.Name = "txttype";
			global::System.Windows.Forms.Control txttype2 = this.txttype;
			size = new global::System.Drawing.Size(51, 16);
			txttype2.Size = size;
			this.txttype.TabIndex = 85;
			this.txttype.Text = "Label5";
			this.Timer2.Interval = 1;
			global::System.Windows.Forms.Control button12 = this.Button6;
			location = new global::System.Drawing.Point(38, 395);
			button12.Location = location;
			this.Button6.Name = "Button6";
			global::System.Windows.Forms.Control button13 = this.Button6;
			size = new global::System.Drawing.Size(72, 23);
			button13.Size = size;
			this.Button6.TabIndex = 87;
			this.Button6.Text = "Sri";
			this.Button6.UseVisualStyleBackColor = true;
			this.DataSelf.BackgroundColor = global::System.Drawing.SystemColors.Control;
			this.DataSelf.Columns.AddRange(new global::System.Windows.Forms.DataGridViewColumn[]
			{
				this.DataGridViewTextBoxColumn1,
				this.DataGridViewTextBoxColumn2,
				this.DataGridViewTextBoxColumn3
			});
			this.DataSelf.GridColor = global::System.Drawing.Color.FromArgb(128, 128, 255);
			global::System.Windows.Forms.Control dataSelf = this.DataSelf;
			location = new global::System.Drawing.Point(263, 446);
			dataSelf.Location = location;
			this.DataSelf.Name = "DataSelf";
			this.DataSelf.RowHeadersVisible = false;
			global::System.Windows.Forms.Control dataSelf2 = this.DataSelf;
			size = new global::System.Drawing.Size(161, 100);
			dataSelf2.Size = size;
			this.DataSelf.TabIndex = 88;
			this.DataGridViewTextBoxColumn1.HeaderText = "Self";
			this.DataGridViewTextBoxColumn1.Name = "DataGridViewTextBoxColumn1";
			this.DataGridViewTextBoxColumn1.ReadOnly = true;
			this.DataGridViewTextBoxColumn2.HeaderText = "Amount";
			this.DataGridViewTextBoxColumn2.Name = "DataGridViewTextBoxColumn2";
			this.DataGridViewTextBoxColumn2.ReadOnly = true;
			this.DataGridViewTextBoxColumn2.Width = 50;
			this.DataGridViewTextBoxColumn3.HeaderText = "Remark";
			this.DataGridViewTextBoxColumn3.Name = "DataGridViewTextBoxColumn3";
			this.DataGridViewTextBoxColumn3.ReadOnly = true;
			this.DataGridViewTextBoxColumn3.Width = 300;
			this.Dataagent.BackgroundColor = global::System.Drawing.SystemColors.Control;
			this.Dataagent.Columns.AddRange(new global::System.Windows.Forms.DataGridViewColumn[]
			{
				this.DataGridViewTextBoxColumn4,
				this.DataGridViewTextBoxColumn5,
				this.DataGridViewTextBoxColumn6
			});
			this.Dataagent.GridColor = global::System.Drawing.Color.FromArgb(128, 128, 255);
			global::System.Windows.Forms.Control dataagent = this.Dataagent;
			location = new global::System.Drawing.Point(430, 446);
			dataagent.Location = location;
			this.Dataagent.Name = "Dataagent";
			this.Dataagent.RowHeadersVisible = false;
			global::System.Windows.Forms.Control dataagent2 = this.Dataagent;
			size = new global::System.Drawing.Size(174, 100);
			dataagent2.Size = size;
			this.Dataagent.TabIndex = 89;
			this.DataGridViewTextBoxColumn4.HeaderText = "Agent";
			this.DataGridViewTextBoxColumn4.Name = "DataGridViewTextBoxColumn4";
			this.DataGridViewTextBoxColumn4.ReadOnly = true;
			this.DataGridViewTextBoxColumn5.HeaderText = "Amount";
			this.DataGridViewTextBoxColumn5.Name = "DataGridViewTextBoxColumn5";
			this.DataGridViewTextBoxColumn5.ReadOnly = true;
			this.DataGridViewTextBoxColumn5.Width = 50;
			this.DataGridViewTextBoxColumn6.HeaderText = "Remark";
			this.DataGridViewTextBoxColumn6.Name = "DataGridViewTextBoxColumn6";
			this.DataGridViewTextBoxColumn6.ReadOnly = true;
			this.DataGridViewTextBoxColumn6.Width = 300;
			this.Datapatner.BackgroundColor = global::System.Drawing.SystemColors.Control;
			this.Datapatner.Columns.AddRange(new global::System.Windows.Forms.DataGridViewColumn[]
			{
				this.DataGridViewTextBoxColumn7,
				this.DataGridViewTextBoxColumn8,
				this.DataGridViewTextBoxColumn9
			});
			this.Datapatner.GridColor = global::System.Drawing.Color.FromArgb(128, 128, 255);
			global::System.Windows.Forms.Control datapatner = this.Datapatner;
			location = new global::System.Drawing.Point(610, 446);
			datapatner.Location = location;
			this.Datapatner.Name = "Datapatner";
			this.Datapatner.RowHeadersVisible = false;
			global::System.Windows.Forms.Control datapatner2 = this.Datapatner;
			size = new global::System.Drawing.Size(162, 100);
			datapatner2.Size = size;
			this.Datapatner.TabIndex = 90;
			this.DataGridViewTextBoxColumn7.HeaderText = "Patner";
			this.DataGridViewTextBoxColumn7.Name = "DataGridViewTextBoxColumn7";
			this.DataGridViewTextBoxColumn7.ReadOnly = true;
			this.DataGridViewTextBoxColumn8.HeaderText = "Amount";
			this.DataGridViewTextBoxColumn8.Name = "DataGridViewTextBoxColumn8";
			this.DataGridViewTextBoxColumn8.ReadOnly = true;
			this.DataGridViewTextBoxColumn8.Width = 50;
			this.DataGridViewTextBoxColumn9.HeaderText = "Remark";
			this.DataGridViewTextBoxColumn9.Name = "DataGridViewTextBoxColumn9";
			this.DataGridViewTextBoxColumn9.ReadOnly = true;
			this.DataGridViewTextBoxColumn9.Width = 300;
			this.Datacomision.BackgroundColor = global::System.Drawing.SystemColors.Control;
			this.Datacomision.Columns.AddRange(new global::System.Windows.Forms.DataGridViewColumn[]
			{
				this.DataGridViewTextBoxColumn10,
				this.DataGridViewTextBoxColumn11,
				this.DataGridViewTextBoxColumn12
			});
			this.Datacomision.GridColor = global::System.Drawing.Color.FromArgb(128, 128, 255);
			global::System.Windows.Forms.Control datacomision = this.Datacomision;
			location = new global::System.Drawing.Point(778, 446);
			datacomision.Location = location;
			this.Datacomision.Name = "Datacomision";
			this.Datacomision.RowHeadersVisible = false;
			global::System.Windows.Forms.Control datacomision2 = this.Datacomision;
			size = new global::System.Drawing.Size(160, 100);
			datacomision2.Size = size;
			this.Datacomision.TabIndex = 91;
			this.DataGridViewTextBoxColumn10.HeaderText = "Commision";
			this.DataGridViewTextBoxColumn10.Name = "DataGridViewTextBoxColumn10";
			this.DataGridViewTextBoxColumn10.ReadOnly = true;
			this.DataGridViewTextBoxColumn11.HeaderText = "Amount";
			this.DataGridViewTextBoxColumn11.Name = "DataGridViewTextBoxColumn11";
			this.DataGridViewTextBoxColumn11.ReadOnly = true;
			this.DataGridViewTextBoxColumn11.Width = 50;
			this.DataGridViewTextBoxColumn12.HeaderText = "Remark";
			this.DataGridViewTextBoxColumn12.Name = "DataGridViewTextBoxColumn12";
			this.DataGridViewTextBoxColumn12.ReadOnly = true;
			this.DataGridViewTextBoxColumn12.Width = 300;
			this.DataGridView2.AllowUserToAddRows = false;
			this.DataGridView2.AllowUserToDeleteRows = false;
			this.DataGridView2.BackgroundColor = global::System.Drawing.SystemColors.Control;
			this.DataGridView2.Columns.AddRange(new global::System.Windows.Forms.DataGridViewColumn[]
			{
				this.DataGridViewTextBoxColumn13,
				this.DataGridViewTextBoxColumn14,
				this.DataGridViewTextBoxColumn15
			});
			this.DataGridView2.GridColor = global::System.Drawing.Color.FromArgb(128, 128, 255);
			global::System.Windows.Forms.Control dataGridView3 = this.DataGridView2;
			location = new global::System.Drawing.Point(958, 446);
			dataGridView3.Location = location;
			this.DataGridView2.Name = "DataGridView2";
			this.DataGridView2.ReadOnly = true;
			this.DataGridView2.RowHeadersVisible = false;
			global::System.Windows.Forms.Control dataGridView4 = this.DataGridView2;
			size = new global::System.Drawing.Size(369, 100);
			dataGridView4.Size = size;
			this.DataGridView2.TabIndex = 92;
			this.DataGridViewTextBoxColumn13.HeaderText = "SRHI";
			this.DataGridViewTextBoxColumn13.Name = "DataGridViewTextBoxColumn13";
			this.DataGridViewTextBoxColumn13.ReadOnly = true;
			this.DataGridViewTextBoxColumn14.HeaderText = "Amount";
			this.DataGridViewTextBoxColumn14.Name = "DataGridViewTextBoxColumn14";
			this.DataGridViewTextBoxColumn14.ReadOnly = true;
			this.DataGridViewTextBoxColumn15.HeaderText = "Remark";
			this.DataGridViewTextBoxColumn15.Name = "DataGridViewTextBoxColumn15";
			this.DataGridViewTextBoxColumn15.ReadOnly = true;
			this.DataGridViewTextBoxColumn15.Width = 300;
			global::System.Windows.Forms.Control button14 = this.Button7;
			location = new global::System.Drawing.Point(132, 392);
			button14.Location = location;
			this.Button7.Name = "Button7";
			global::System.Windows.Forms.Control button15 = this.Button7;
			size = new global::System.Drawing.Size(93, 29);
			button15.Size = size;
			this.Button7.TabIndex = 93;
			this.Button7.Text = "Save Grid";
			this.Button7.UseVisualStyleBackColor = true;
			global::System.Windows.Forms.Control button16 = this.Button8;
			location = new global::System.Drawing.Point(231, 392);
			button16.Location = location;
			this.Button8.Name = "Button8";
			global::System.Windows.Forms.Control button17 = this.Button8;
			size = new global::System.Drawing.Size(93, 29);
			button17.Size = size;
			this.Button8.TabIndex = 94;
			this.Button8.Text = "Grid_Self";
			this.Button8.UseVisualStyleBackColor = true;
			global::System.Windows.Forms.Control button18 = this.Button9;
			location = new global::System.Drawing.Point(330, 392);
			button18.Location = location;
			this.Button9.Name = "Button9";
			global::System.Windows.Forms.Control button19 = this.Button9;
			size = new global::System.Drawing.Size(93, 29);
			button19.Size = size;
			this.Button9.TabIndex = 95;
			this.Button9.Text = "Grid_Agent";
			this.Button9.UseVisualStyleBackColor = true;
			global::System.Windows.Forms.Control button20 = this.Button10;
			location = new global::System.Drawing.Point(429, 392);
			button20.Location = location;
			this.Button10.Name = "Button10";
			global::System.Windows.Forms.Control button21 = this.Button10;
			size = new global::System.Drawing.Size(93, 29);
			button21.Size = size;
			this.Button10.TabIndex = 96;
			this.Button10.Text = "Grid_Patner";
			this.Button10.UseVisualStyleBackColor = true;
			global::System.Windows.Forms.Control button22 = this.Button11;
			location = new global::System.Drawing.Point(528, 392);
			button22.Location = location;
			this.Button11.Name = "Button11";
			global::System.Windows.Forms.Control button23 = this.Button11;
			size = new global::System.Drawing.Size(93, 29);
			button23.Size = size;
			this.Button11.TabIndex = 97;
			this.Button11.Text = "Grid_commiss";
			this.Button11.UseVisualStyleBackColor = true;
			global::System.Windows.Forms.Control button24 = this.Button12;
			location = new global::System.Drawing.Point(627, 392);
			button24.Location = location;
			this.Button12.Name = "Button12";
			global::System.Windows.Forms.Control button25 = this.Button12;
			size = new global::System.Drawing.Size(93, 29);
			button25.Size = size;
			this.Button12.TabIndex = 98;
			this.Button12.Text = "Grid_Srhi";
			this.Button12.UseVisualStyleBackColor = true;
			this.AgentTransfar.FormattingEnabled = true;
			global::System.Windows.Forms.Control agentTransfar = this.AgentTransfar;
			location = new global::System.Drawing.Point(132, 84);
			agentTransfar.Location = location;
			this.AgentTransfar.Name = "AgentTransfar";
			global::System.Windows.Forms.Control agentTransfar2 = this.AgentTransfar;
			size = new global::System.Drawing.Size(121, 24);
			agentTransfar2.Size = size;
			this.AgentTransfar.TabIndex = 101;
			this.PatnareTransfar.FormattingEnabled = true;
			global::System.Windows.Forms.Control patnareTransfar = this.PatnareTransfar;
			location = new global::System.Drawing.Point(132, 120);
			patnareTransfar.Location = location;
			this.PatnareTransfar.Name = "PatnareTransfar";
			global::System.Windows.Forms.Control patnareTransfar2 = this.PatnareTransfar;
			size = new global::System.Drawing.Size(121, 24);
			patnareTransfar2.Size = size;
			this.PatnareTransfar.TabIndex = 102;
			this.Label5.AutoSize = true;
			global::System.Windows.Forms.Control label11 = this.Label5;
			location = new global::System.Drawing.Point(937, 374);
			label11.Location = location;
			this.Label5.Name = "Label5";
			global::System.Windows.Forms.Control label12 = this.Label5;
			size = new global::System.Drawing.Size(51, 16);
			label12.Size = size;
			this.Label5.TabIndex = 103;
			this.Label5.Text = "Label5";
			this.Label5.Visible = false;
			this.txtdate.Format = global::System.Windows.Forms.DateTimePickerFormat.Short;
			global::System.Windows.Forms.Control txtdate = this.txtdate;
			location = new global::System.Drawing.Point(108, 160);
			txtdate.Location = location;
			this.txtdate.Name = "txtdate";
			global::System.Windows.Forms.Control txtdate2 = this.txtdate;
			size = new global::System.Drawing.Size(117, 22);
			txtdate2.Size = size;
			this.txtdate.TabIndex = 100;
			global::System.Windows.Forms.Control panel = this.Panel1;
			location = new global::System.Drawing.Point(0, 324);
			panel.Location = location;
			this.Panel1.Name = "Panel1";
			global::System.Windows.Forms.Control panel2 = this.Panel1;
			size = new global::System.Drawing.Size(324, 10);
			panel2.Size = size;
			this.Panel1.TabIndex = 104;
			global::System.Windows.Forms.Control panel3 = this.Panel2;
			location = new global::System.Drawing.Point(852, 250);
			panel3.Location = location;
			this.Panel2.Name = "Panel2";
			global::System.Windows.Forms.Control panel4 = this.Panel2;
			size = new global::System.Drawing.Size(421, 10);
			panel4.Size = size;
			this.Panel2.TabIndex = 105;
			global::System.Windows.Forms.Control panel5 = this.Panel3;
			location = new global::System.Drawing.Point(17, 581);
			panel5.Location = location;
			this.Panel3.Name = "Panel3";
			global::System.Windows.Forms.Control panel6 = this.Panel3;
			size = new global::System.Drawing.Size(1328, 38);
			panel6.Size = size;
			this.Panel3.TabIndex = 106;
			global::System.Drawing.SizeF autoScaleDimensions = new global::System.Drawing.SizeF(8f, 16f);
			this.AutoScaleDimensions = autoScaleDimensions;
			this.AutoScaleMode = global::System.Windows.Forms.AutoScaleMode.Font;
			this.CancelButton = this.Button2;
			size = new global::System.Drawing.Size(1276, 742);
			this.ClientSize = size;
			this.ControlBox = false;
			this.Controls.Add(this.Panel3);
			this.Controls.Add(this.Panel2);
			this.Controls.Add(this.Label4);
			this.Controls.Add(this.Panel1);
			this.Controls.Add(this.txtdeclard);
			this.Controls.Add(this.txtdate);
			this.Controls.Add(this.Label5);
			this.Controls.Add(this.PatnareTransfar);
			this.Controls.Add(this.AgentTransfar);
			this.Controls.Add(this.Button12);
			this.Controls.Add(this.Button11);
			this.Controls.Add(this.Button10);
			this.Controls.Add(this.Button9);
			this.Controls.Add(this.Button8);
			this.Controls.Add(this.Button7);
			this.Controls.Add(this.DataGridView2);
			this.Controls.Add(this.Datacomision);
			this.Controls.Add(this.Datapatner);
			this.Controls.Add(this.Dataagent);
			this.Controls.Add(this.DataSelf);
			this.Controls.Add(this.Button6);
			this.Controls.Add(this.datagridmen);
			this.Controls.Add(this.txttype);
			this.Controls.Add(this.txtcomission);
			this.Controls.Add(this.txtpatnarname);
			this.Controls.Add(this.txtpatnarparsent);
			this.Controls.Add(this.txtagentname);
			this.Controls.Add(this.txtpartyname);
			this.Controls.Add(this.Button5);
			this.Controls.Add(this.txtself);
			this.Controls.Add(this.txtagentparsent);
			this.Controls.Add(this.TextBox3);
			this.Controls.Add(this.TextBox1);
			this.Controls.Add(this.DataGridView1);
			this.Controls.Add(this.Button4);
			this.Controls.Add(this.TextBox2);
			this.Controls.Add(this.Button3);
			this.Controls.Add(this.txtpname);
			this.Controls.Add(this.Button1);
			this.Controls.Add(this.Button2);
			this.Controls.Add(this.txtdecl);
			this.Controls.Add(this.Save);
			this.Controls.Add(this.GroupBox3);
			this.Controls.Add(this.Label1);
			this.Controls.Add(this.Label2);
			this.Font = new global::System.Drawing.Font("Arial", 9.75f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Icon = (global::System.Drawing.Icon)componentResourceManager.GetObject("$this.Icon");
			padding = new global::System.Windows.Forms.Padding(4);
			this.Margin = padding;
			this.MaximizeBox = false;
			this.MinimizeBox = false;
			this.Name = "SessionDelear";
			this.Text = "SessionDelear";
			this.WindowState = global::System.Windows.Forms.FormWindowState.Maximized;
			this.GroupBox3.ResumeLayout(false);
			this.GroupBox3.PerformLayout();
			((global::System.ComponentModel.ISupportInitialize)this.datagridmen).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.DataGridView1).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.DataSelf).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.Dataagent).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.Datapatner).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.Datacomision).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.DataGridView2).EndInit();
			this.ResumeLayout(false);
			this.PerformLayout();
		}

		// Token: 0x04000CE5 RID: 3301
		private global::System.ComponentModel.IContainer components;
	}
}
